// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: orcan/v1/product_detail.proto

package orcanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     uint32                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	SortOrder     int32                  `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductDetail) Reset() {
	*x = ProductDetail{}
	mi := &file_orcan_v1_product_detail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDetail) ProtoMessage() {}

func (x *ProductDetail) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_detail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDetail.ProtoReflect.Descriptor instead.
func (*ProductDetail) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_detail_proto_rawDescGZIP(), []int{0}
}

func (x *ProductDetail) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductDetail) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductDetail) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ProductDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductDetail) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *ProductDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductDetail) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListProductDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     *uint32                `protobuf:"varint,1,opt,name=product_id,json=productId,proto3,oneof" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductDetailsRequest) Reset() {
	*x = ListProductDetailsRequest{}
	mi := &file_orcan_v1_product_detail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductDetailsRequest) ProtoMessage() {}

func (x *ListProductDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_detail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductDetailsRequest.ProtoReflect.Descriptor instead.
func (*ListProductDetailsRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_detail_proto_rawDescGZIP(), []int{1}
}

func (x *ListProductDetailsRequest) GetProductId() uint32 {
	if x != nil && x.ProductId != nil {
		return *x.ProductId
	}
	return 0
}

type ListProductDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       []*ProductDetail       `protobuf:"bytes,1,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductDetailsResponse) Reset() {
	*x = ListProductDetailsResponse{}
	mi := &file_orcan_v1_product_detail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductDetailsResponse) ProtoMessage() {}

func (x *ListProductDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_detail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductDetailsResponse.ProtoReflect.Descriptor instead.
func (*ListProductDetailsResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_detail_proto_rawDescGZIP(), []int{2}
}

func (x *ListProductDetailsResponse) GetDetails() []*ProductDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

type GetProductDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductDetailRequest) Reset() {
	*x = GetProductDetailRequest{}
	mi := &file_orcan_v1_product_detail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductDetailRequest) ProtoMessage() {}

func (x *GetProductDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_detail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductDetailRequest.ProtoReflect.Descriptor instead.
func (*GetProductDetailRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_detail_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductDetailRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProductDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        *ProductDetail         `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductDetailResponse) Reset() {
	*x = GetProductDetailResponse{}
	mi := &file_orcan_v1_product_detail_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductDetailResponse) ProtoMessage() {}

func (x *GetProductDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_detail_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductDetailResponse.ProtoReflect.Descriptor instead.
func (*GetProductDetailResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_detail_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductDetailResponse) GetDetail() *ProductDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type CreateProductDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SortOrder     int32                  `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductDetailRequest) Reset() {
	*x = CreateProductDetailRequest{}
	mi := &file_orcan_v1_product_detail_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductDetailRequest) ProtoMessage() {}

func (x *CreateProductDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_detail_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductDetailRequest.ProtoReflect.Descriptor instead.
func (*CreateProductDetailRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_detail_proto_rawDescGZIP(), []int{5}
}

func (x *CreateProductDetailRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateProductDetailRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CreateProductDetailRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductDetailRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type CreateProductDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        *ProductDetail         `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductDetailResponse) Reset() {
	*x = CreateProductDetailResponse{}
	mi := &file_orcan_v1_product_detail_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductDetailResponse) ProtoMessage() {}

func (x *CreateProductDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_detail_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductDetailResponse.ProtoReflect.Descriptor instead.
func (*CreateProductDetailResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_detail_proto_rawDescGZIP(), []int{6}
}

func (x *CreateProductDetailResponse) GetDetail() *ProductDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type UpdateProductDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     uint32                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	SortOrder     int32                  `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductDetailRequest) Reset() {
	*x = UpdateProductDetailRequest{}
	mi := &file_orcan_v1_product_detail_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductDetailRequest) ProtoMessage() {}

func (x *UpdateProductDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_detail_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductDetailRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductDetailRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_detail_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProductDetailRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductDetailRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateProductDetailRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *UpdateProductDetailRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductDetailRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type UpdateProductDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        *ProductDetail         `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductDetailResponse) Reset() {
	*x = UpdateProductDetailResponse{}
	mi := &file_orcan_v1_product_detail_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductDetailResponse) ProtoMessage() {}

func (x *UpdateProductDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_detail_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductDetailResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductDetailResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_detail_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProductDetailResponse) GetDetail() *ProductDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type DeleteProductDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductDetailRequest) Reset() {
	*x = DeleteProductDetailRequest{}
	mi := &file_orcan_v1_product_detail_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductDetailRequest) ProtoMessage() {}

func (x *DeleteProductDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_detail_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductDetailRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductDetailRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_detail_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteProductDetailRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteProductDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductDetailResponse) Reset() {
	*x = DeleteProductDetailResponse{}
	mi := &file_orcan_v1_product_detail_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductDetailResponse) ProtoMessage() {}

func (x *DeleteProductDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_detail_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductDetailResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductDetailResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_detail_proto_rawDescGZIP(), []int{10}
}

var File_orcan_v1_product_detail_proto protoreflect.FileDescriptor

const file_orcan_v1_product_detail_proto_rawDesc = "" +
	"\n" +
	"\x1dorcan/v1/product_detail.proto\x12\borcan.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x02\n" +
	"\rProductDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\rR\tproductId\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x05R\tsortOrder\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"N\n" +
	"\x19ListProductDetailsRequest\x12\"\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rH\x00R\tproductId\x88\x01\x01B\r\n" +
	"\v_product_id\"O\n" +
	"\x1aListProductDetailsResponse\x121\n" +
	"\adetails\x18\x01 \x03(\v2\x17.orcan.v1.ProductDetailR\adetails\")\n" +
	"\x17GetProductDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"K\n" +
	"\x18GetProductDetailResponse\x12/\n" +
	"\x06detail\x18\x01 \x01(\v2\x17.orcan.v1.ProductDetailR\x06detail\"\x99\x01\n" +
	"\x1aCreateProductDetailRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05R\tsortOrder\"N\n" +
	"\x1bCreateProductDetailResponse\x12/\n" +
	"\x06detail\x18\x01 \x01(\v2\x17.orcan.v1.ProductDetailR\x06detail\"\xa9\x01\n" +
	"\x1aUpdateProductDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\rR\tproductId\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x05R\tsortOrder\"N\n" +
	"\x1bUpdateProductDetailResponse\x12/\n" +
	"\x06detail\x18\x01 \x01(\v2\x17.orcan.v1.ProductDetailR\x06detail\",\n" +
	"\x1aDeleteProductDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x1d\n" +
	"\x1bDeleteProductDetailResponse2\xfe\x03\n" +
	"\x14ProductDetailService\x12_\n" +
	"\x12ListProductDetails\x12#.orcan.v1.ListProductDetailsRequest\x1a$.orcan.v1.ListProductDetailsResponse\x12Y\n" +
	"\x10GetProductDetail\x12!.orcan.v1.GetProductDetailRequest\x1a\".orcan.v1.GetProductDetailResponse\x12b\n" +
	"\x13CreateProductDetail\x12$.orcan.v1.CreateProductDetailRequest\x1a%.orcan.v1.CreateProductDetailResponse\x12b\n" +
	"\x13UpdateProductDetail\x12$.orcan.v1.UpdateProductDetailRequest\x1a%.orcan.v1.UpdateProductDetailResponse\x12b\n" +
	"\x13DeleteProductDetail\x12$.orcan.v1.DeleteProductDetailRequest\x1a%.orcan.v1.DeleteProductDetailResponseBQZOgithub.com/asamigentoku/PinguCoin/server/orcan-api/internal/pb/orcan/v1;orcanv1b\x06proto3"

var (
	file_orcan_v1_product_detail_proto_rawDescOnce sync.Once
	file_orcan_v1_product_detail_proto_rawDescData []byte
)

func file_orcan_v1_product_detail_proto_rawDescGZIP() []byte {
	file_orcan_v1_product_detail_proto_rawDescOnce.Do(func() {
		file_orcan_v1_product_detail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orcan_v1_product_detail_proto_rawDesc), len(file_orcan_v1_product_detail_proto_rawDesc)))
	})
	return file_orcan_v1_product_detail_proto_rawDescData
}

var file_orcan_v1_product_detail_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_orcan_v1_product_detail_proto_goTypes = []any{
	(*ProductDetail)(nil),               // 0: orcan.v1.ProductDetail
	(*ListProductDetailsRequest)(nil),   // 1: orcan.v1.ListProductDetailsRequest
	(*ListProductDetailsResponse)(nil),  // 2: orcan.v1.ListProductDetailsResponse
	(*GetProductDetailRequest)(nil),     // 3: orcan.v1.GetProductDetailRequest
	(*GetProductDetailResponse)(nil),    // 4: orcan.v1.GetProductDetailResponse
	(*CreateProductDetailRequest)(nil),  // 5: orcan.v1.CreateProductDetailRequest
	(*CreateProductDetailResponse)(nil), // 6: orcan.v1.CreateProductDetailResponse
	(*UpdateProductDetailRequest)(nil),  // 7: orcan.v1.UpdateProductDetailRequest
	(*UpdateProductDetailResponse)(nil), // 8: orcan.v1.UpdateProductDetailResponse
	(*DeleteProductDetailRequest)(nil),  // 9: orcan.v1.DeleteProductDetailRequest
	(*DeleteProductDetailResponse)(nil), // 10: orcan.v1.DeleteProductDetailResponse
	(*timestamppb.Timestamp)(nil),       // 11: google.protobuf.Timestamp
}
var file_orcan_v1_product_detail_proto_depIdxs = []int32{
	11, // 0: orcan.v1.ProductDetail.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: orcan.v1.ProductDetail.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: orcan.v1.ListProductDetailsResponse.details:type_name -> orcan.v1.ProductDetail
	0,  // 3: orcan.v1.GetProductDetailResponse.detail:type_name -> orcan.v1.ProductDetail
	0,  // 4: orcan.v1.CreateProductDetailResponse.detail:type_name -> orcan.v1.ProductDetail
	0,  // 5: orcan.v1.UpdateProductDetailResponse.detail:type_name -> orcan.v1.ProductDetail
	1,  // 6: orcan.v1.ProductDetailService.ListProductDetails:input_type -> orcan.v1.ListProductDetailsRequest
	3,  // 7: orcan.v1.ProductDetailService.GetProductDetail:input_type -> orcan.v1.GetProductDetailRequest
	5,  // 8: orcan.v1.ProductDetailService.CreateProductDetail:input_type -> orcan.v1.CreateProductDetailRequest
	7,  // 9: orcan.v1.ProductDetailService.UpdateProductDetail:input_type -> orcan.v1.UpdateProductDetailRequest
	9,  // 10: orcan.v1.ProductDetailService.DeleteProductDetail:input_type -> orcan.v1.DeleteProductDetailRequest
	2,  // 11: orcan.v1.ProductDetailService.ListProductDetails:output_type -> orcan.v1.ListProductDetailsResponse
	4,  // 12: orcan.v1.ProductDetailService.GetProductDetail:output_type -> orcan.v1.GetProductDetailResponse
	6,  // 13: orcan.v1.ProductDetailService.CreateProductDetail:output_type -> orcan.v1.CreateProductDetailResponse
	8,  // 14: orcan.v1.ProductDetailService.UpdateProductDetail:output_type -> orcan.v1.UpdateProductDetailResponse
	10, // 15: orcan.v1.ProductDetailService.DeleteProductDetail:output_type -> orcan.v1.DeleteProductDetailResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_orcan_v1_product_detail_proto_init() }
func file_orcan_v1_product_detail_proto_init() {
	if File_orcan_v1_product_detail_proto != nil {
		return
	}
	file_orcan_v1_product_detail_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orcan_v1_product_detail_proto_rawDesc), len(file_orcan_v1_product_detail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orcan_v1_product_detail_proto_goTypes,
		DependencyIndexes: file_orcan_v1_product_detail_proto_depIdxs,
		MessageInfos:      file_orcan_v1_product_detail_proto_msgTypes,
	}.Build()
	File_orcan_v1_product_detail_proto = out.File
	file_orcan_v1_product_detail_proto_goTypes = nil
	file_orcan_v1_product_detail_proto_depIdxs = nil
}
