// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: orcan/v1/product_asset.proto

package orcanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductAssetPurpose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsPublic      bool                   `protobuf:"varint,3,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductAssetPurpose) Reset() {
	*x = ProductAssetPurpose{}
	mi := &file_orcan_v1_product_asset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductAssetPurpose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAssetPurpose) ProtoMessage() {}

func (x *ProductAssetPurpose) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_asset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAssetPurpose.ProtoReflect.Descriptor instead.
func (*ProductAssetPurpose) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_asset_proto_rawDescGZIP(), []int{0}
}

func (x *ProductAssetPurpose) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductAssetPurpose) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductAssetPurpose) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type ProductAsset struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId        uint32                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	PurposeId        uint32                 `protobuf:"varint,3,opt,name=purpose_id,json=purposeId,proto3" json:"purpose_id,omitempty"`
	Purpose          *ProductAssetPurpose   `protobuf:"bytes,4,opt,name=purpose,proto3" json:"purpose,omitempty"`
	StorageUrl       string                 `protobuf:"bytes,5,opt,name=storage_url,json=storageUrl,proto3" json:"storage_url,omitempty"`
	OriginalFilename string                 `protobuf:"bytes,6,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"`
	ContentType      string                 `protobuf:"bytes,7,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	FileSize         int64                  `protobuf:"varint,8,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Description      string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	SortOrder        int32                  `protobuf:"varint,10,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	IsPrimary        bool                   `protobuf:"varint,11,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	Metadata         string                 `protobuf:"bytes,12,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProductAsset) Reset() {
	*x = ProductAsset{}
	mi := &file_orcan_v1_product_asset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAsset) ProtoMessage() {}

func (x *ProductAsset) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_asset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAsset.ProtoReflect.Descriptor instead.
func (*ProductAsset) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_asset_proto_rawDescGZIP(), []int{1}
}

func (x *ProductAsset) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductAsset) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductAsset) GetPurposeId() uint32 {
	if x != nil {
		return x.PurposeId
	}
	return 0
}

func (x *ProductAsset) GetPurpose() *ProductAssetPurpose {
	if x != nil {
		return x.Purpose
	}
	return nil
}

func (x *ProductAsset) GetStorageUrl() string {
	if x != nil {
		return x.StorageUrl
	}
	return ""
}

func (x *ProductAsset) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

func (x *ProductAsset) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ProductAsset) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *ProductAsset) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductAsset) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *ProductAsset) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *ProductAsset) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *ProductAsset) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductAsset) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListProductAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	PurposeId     *uint32                `protobuf:"varint,2,opt,name=purpose_id,json=purposeId,proto3,oneof" json:"purpose_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductAssetsRequest) Reset() {
	*x = ListProductAssetsRequest{}
	mi := &file_orcan_v1_product_asset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductAssetsRequest) ProtoMessage() {}

func (x *ListProductAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_asset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductAssetsRequest.ProtoReflect.Descriptor instead.
func (*ListProductAssetsRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_asset_proto_rawDescGZIP(), []int{2}
}

func (x *ListProductAssetsRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ListProductAssetsRequest) GetPurposeId() uint32 {
	if x != nil && x.PurposeId != nil {
		return *x.PurposeId
	}
	return 0
}

type ListProductAssetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*ProductAsset        `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductAssetsResponse) Reset() {
	*x = ListProductAssetsResponse{}
	mi := &file_orcan_v1_product_asset_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductAssetsResponse) ProtoMessage() {}

func (x *ListProductAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_asset_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductAssetsResponse.ProtoReflect.Descriptor instead.
func (*ListProductAssetsResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_asset_proto_rawDescGZIP(), []int{3}
}

func (x *ListProductAssetsResponse) GetAssets() []*ProductAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type GetProductAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductAssetRequest) Reset() {
	*x = GetProductAssetRequest{}
	mi := &file_orcan_v1_product_asset_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductAssetRequest) ProtoMessage() {}

func (x *GetProductAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_asset_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductAssetRequest.ProtoReflect.Descriptor instead.
func (*GetProductAssetRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_asset_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductAssetRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProductAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *ProductAsset          `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductAssetResponse) Reset() {
	*x = GetProductAssetResponse{}
	mi := &file_orcan_v1_product_asset_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductAssetResponse) ProtoMessage() {}

func (x *GetProductAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_asset_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductAssetResponse.ProtoReflect.Descriptor instead.
func (*GetProductAssetResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_asset_proto_rawDescGZIP(), []int{5}
}

func (x *GetProductAssetResponse) GetAsset() *ProductAsset {
	if x != nil {
		return x.Asset
	}
	return nil
}

type GetProductAssetUploadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     uint32                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	PurposeId     uint32                 `protobuf:"varint,3,opt,name=purpose_id,json=purposeId,proto3" json:"purpose_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductAssetUploadURLRequest) Reset() {
	*x = GetProductAssetUploadURLRequest{}
	mi := &file_orcan_v1_product_asset_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductAssetUploadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductAssetUploadURLRequest) ProtoMessage() {}

func (x *GetProductAssetUploadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_asset_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductAssetUploadURLRequest.ProtoReflect.Descriptor instead.
func (*GetProductAssetUploadURLRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_asset_proto_rawDescGZIP(), []int{6}
}

func (x *GetProductAssetUploadURLRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetProductAssetUploadURLRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *GetProductAssetUploadURLRequest) GetPurposeId() uint32 {
	if x != nil {
		return x.PurposeId
	}
	return 0
}

type GetProductAssetUploadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlobEndpoint  string                 `protobuf:"bytes,1,opt,name=blob_endpoint,json=blobEndpoint,proto3" json:"blob_endpoint,omitempty"`
	Container     string                 `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
	PathPrefix    string                 `protobuf:"bytes,3,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	SasToken      string                 `protobuf:"bytes,4,opt,name=sas_token,json=sasToken,proto3" json:"sas_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductAssetUploadURLResponse) Reset() {
	*x = GetProductAssetUploadURLResponse{}
	mi := &file_orcan_v1_product_asset_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductAssetUploadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductAssetUploadURLResponse) ProtoMessage() {}

func (x *GetProductAssetUploadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_asset_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductAssetUploadURLResponse.ProtoReflect.Descriptor instead.
func (*GetProductAssetUploadURLResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_asset_proto_rawDescGZIP(), []int{7}
}

func (x *GetProductAssetUploadURLResponse) GetBlobEndpoint() string {
	if x != nil {
		return x.BlobEndpoint
	}
	return ""
}

func (x *GetProductAssetUploadURLResponse) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *GetProductAssetUploadURLResponse) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *GetProductAssetUploadURLResponse) GetSasToken() string {
	if x != nil {
		return x.SasToken
	}
	return ""
}

func (x *GetProductAssetUploadURLResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ConfirmProductAssetUploadRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId        uint32                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	PurposeId        uint32                 `protobuf:"varint,3,opt,name=purpose_id,json=purposeId,proto3" json:"purpose_id,omitempty"`
	FileUrl          string                 `protobuf:"bytes,4,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	OriginalFilename string                 `protobuf:"bytes,5,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"`
	ContentType      string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	FileSize         int64                  `protobuf:"varint,7,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Description      string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	SortOrder        int32                  `protobuf:"varint,9,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	IsPrimary        bool                   `protobuf:"varint,10,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	Metadata         string                 `protobuf:"bytes,11,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfirmProductAssetUploadRequest) Reset() {
	*x = ConfirmProductAssetUploadRequest{}
	mi := &file_orcan_v1_product_asset_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmProductAssetUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmProductAssetUploadRequest) ProtoMessage() {}

func (x *ConfirmProductAssetUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_asset_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmProductAssetUploadRequest.ProtoReflect.Descriptor instead.
func (*ConfirmProductAssetUploadRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_asset_proto_rawDescGZIP(), []int{8}
}

func (x *ConfirmProductAssetUploadRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConfirmProductAssetUploadRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ConfirmProductAssetUploadRequest) GetPurposeId() uint32 {
	if x != nil {
		return x.PurposeId
	}
	return 0
}

func (x *ConfirmProductAssetUploadRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *ConfirmProductAssetUploadRequest) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

func (x *ConfirmProductAssetUploadRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ConfirmProductAssetUploadRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *ConfirmProductAssetUploadRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfirmProductAssetUploadRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *ConfirmProductAssetUploadRequest) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *ConfirmProductAssetUploadRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type ConfirmProductAssetUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *ProductAsset          `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmProductAssetUploadResponse) Reset() {
	*x = ConfirmProductAssetUploadResponse{}
	mi := &file_orcan_v1_product_asset_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmProductAssetUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmProductAssetUploadResponse) ProtoMessage() {}

func (x *ConfirmProductAssetUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_asset_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmProductAssetUploadResponse.ProtoReflect.Descriptor instead.
func (*ConfirmProductAssetUploadResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_asset_proto_rawDescGZIP(), []int{9}
}

func (x *ConfirmProductAssetUploadResponse) GetAsset() *ProductAsset {
	if x != nil {
		return x.Asset
	}
	return nil
}

type DeleteProductAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AssetId       uint32                 `protobuf:"varint,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductAssetRequest) Reset() {
	*x = DeleteProductAssetRequest{}
	mi := &file_orcan_v1_product_asset_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductAssetRequest) ProtoMessage() {}

func (x *DeleteProductAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_asset_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductAssetRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductAssetRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_asset_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteProductAssetRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteProductAssetRequest) GetAssetId() uint32 {
	if x != nil {
		return x.AssetId
	}
	return 0
}

type DeleteProductAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductAssetResponse) Reset() {
	*x = DeleteProductAssetResponse{}
	mi := &file_orcan_v1_product_asset_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductAssetResponse) ProtoMessage() {}

func (x *DeleteProductAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_asset_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductAssetResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductAssetResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_asset_proto_rawDescGZIP(), []int{11}
}

type GetProductAssetDownloadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       uint32                 `protobuf:"varint,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductAssetDownloadURLRequest) Reset() {
	*x = GetProductAssetDownloadURLRequest{}
	mi := &file_orcan_v1_product_asset_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductAssetDownloadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductAssetDownloadURLRequest) ProtoMessage() {}

func (x *GetProductAssetDownloadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_asset_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductAssetDownloadURLRequest.ProtoReflect.Descriptor instead.
func (*GetProductAssetDownloadURLRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_asset_proto_rawDescGZIP(), []int{12}
}

func (x *GetProductAssetDownloadURLRequest) GetAssetId() uint32 {
	if x != nil {
		return x.AssetId
	}
	return 0
}

type GetProductAssetDownloadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DownloadUrl   string                 `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductAssetDownloadURLResponse) Reset() {
	*x = GetProductAssetDownloadURLResponse{}
	mi := &file_orcan_v1_product_asset_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductAssetDownloadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductAssetDownloadURLResponse) ProtoMessage() {}

func (x *GetProductAssetDownloadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_asset_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductAssetDownloadURLResponse.ProtoReflect.Descriptor instead.
func (*GetProductAssetDownloadURLResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_asset_proto_rawDescGZIP(), []int{13}
}

func (x *GetProductAssetDownloadURLResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *GetProductAssetDownloadURLResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_orcan_v1_product_asset_proto protoreflect.FileDescriptor

const file_orcan_v1_product_asset_proto_rawDesc = "" +
	"\n" +
	"\x1corcan/v1/product_asset.proto\x12\borcan.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"V\n" +
	"\x13ProductAssetPurpose\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tis_public\x18\x03 \x01(\bR\bisPublic\"\x95\x04\n" +
	"\fProductAsset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\rR\tproductId\x12\x1d\n" +
	"\n" +
	"purpose_id\x18\x03 \x01(\rR\tpurposeId\x127\n" +
	"\apurpose\x18\x04 \x01(\v2\x1d.orcan.v1.ProductAssetPurposeR\apurpose\x12\x1f\n" +
	"\vstorage_url\x18\x05 \x01(\tR\n" +
	"storageUrl\x12+\n" +
	"\x11original_filename\x18\x06 \x01(\tR\x10originalFilename\x12!\n" +
	"\fcontent_type\x18\a \x01(\tR\vcontentType\x12\x1b\n" +
	"\tfile_size\x18\b \x01(\x03R\bfileSize\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"sort_order\x18\n" +
	" \x01(\x05R\tsortOrder\x12\x1d\n" +
	"\n" +
	"is_primary\x18\v \x01(\bR\tisPrimary\x12\x1a\n" +
	"\bmetadata\x18\f \x01(\tR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"l\n" +
	"\x18ListProductAssetsRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\x12\"\n" +
	"\n" +
	"purpose_id\x18\x02 \x01(\rH\x00R\tpurposeId\x88\x01\x01B\r\n" +
	"\v_purpose_id\"K\n" +
	"\x19ListProductAssetsResponse\x12.\n" +
	"\x06assets\x18\x01 \x03(\v2\x16.orcan.v1.ProductAssetR\x06assets\"(\n" +
	"\x16GetProductAssetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"G\n" +
	"\x17GetProductAssetResponse\x12,\n" +
	"\x05asset\x18\x01 \x01(\v2\x16.orcan.v1.ProductAssetR\x05asset\"x\n" +
	"\x1fGetProductAssetUploadURLRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\rR\tproductId\x12\x1d\n" +
	"\n" +
	"purpose_id\x18\x03 \x01(\rR\tpurposeId\"\xde\x01\n" +
	" GetProductAssetUploadURLResponse\x12#\n" +
	"\rblob_endpoint\x18\x01 \x01(\tR\fblobEndpoint\x12\x1c\n" +
	"\tcontainer\x18\x02 \x01(\tR\tcontainer\x12\x1f\n" +
	"\vpath_prefix\x18\x03 \x01(\tR\n" +
	"pathPrefix\x12\x1b\n" +
	"\tsas_token\x18\x04 \x01(\tR\bsasToken\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xfd\x02\n" +
	" ConfirmProductAssetUploadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\rR\tproductId\x12\x1d\n" +
	"\n" +
	"purpose_id\x18\x03 \x01(\rR\tpurposeId\x12\x19\n" +
	"\bfile_url\x18\x04 \x01(\tR\afileUrl\x12+\n" +
	"\x11original_filename\x18\x05 \x01(\tR\x10originalFilename\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12\x1b\n" +
	"\tfile_size\x18\a \x01(\x03R\bfileSize\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"sort_order\x18\t \x01(\x05R\tsortOrder\x12\x1d\n" +
	"\n" +
	"is_primary\x18\n" +
	" \x01(\bR\tisPrimary\x12\x1a\n" +
	"\bmetadata\x18\v \x01(\tR\bmetadata\"Q\n" +
	"!ConfirmProductAssetUploadResponse\x12,\n" +
	"\x05asset\x18\x01 \x01(\v2\x16.orcan.v1.ProductAssetR\x05asset\"O\n" +
	"\x19DeleteProductAssetRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\rR\aassetId\"\x1c\n" +
	"\x1aDeleteProductAssetResponse\">\n" +
	"!GetProductAssetDownloadURLRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\rR\aassetId\"\x82\x01\n" +
	"\"GetProductAssetDownloadURLResponse\x12!\n" +
	"\fdownload_url\x18\x01 \x01(\tR\vdownloadUrl\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt2\x8e\x05\n" +
	"\x13ProductAssetService\x12\\\n" +
	"\x11ListProductAssets\x12\".orcan.v1.ListProductAssetsRequest\x1a#.orcan.v1.ListProductAssetsResponse\x12V\n" +
	"\x0fGetProductAsset\x12 .orcan.v1.GetProductAssetRequest\x1a!.orcan.v1.GetProductAssetResponse\x12q\n" +
	"\x18GetProductAssetUploadURL\x12).orcan.v1.GetProductAssetUploadURLRequest\x1a*.orcan.v1.GetProductAssetUploadURLResponse\x12t\n" +
	"\x19ConfirmProductAssetUpload\x12*.orcan.v1.ConfirmProductAssetUploadRequest\x1a+.orcan.v1.ConfirmProductAssetUploadResponse\x12_\n" +
	"\x12DeleteProductAsset\x12#.orcan.v1.DeleteProductAssetRequest\x1a$.orcan.v1.DeleteProductAssetResponse\x12w\n" +
	"\x1aGetProductAssetDownloadURL\x12+.orcan.v1.GetProductAssetDownloadURLRequest\x1a,.orcan.v1.GetProductAssetDownloadURLResponseBQZOgithub.com/asamigentoku/PinguCoin/server/orcan-api/internal/pb/orcan/v1;orcanv1b\x06proto3"

var (
	file_orcan_v1_product_asset_proto_rawDescOnce sync.Once
	file_orcan_v1_product_asset_proto_rawDescData []byte
)

func file_orcan_v1_product_asset_proto_rawDescGZIP() []byte {
	file_orcan_v1_product_asset_proto_rawDescOnce.Do(func() {
		file_orcan_v1_product_asset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orcan_v1_product_asset_proto_rawDesc), len(file_orcan_v1_product_asset_proto_rawDesc)))
	})
	return file_orcan_v1_product_asset_proto_rawDescData
}

var file_orcan_v1_product_asset_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_orcan_v1_product_asset_proto_goTypes = []any{
	(*ProductAssetPurpose)(nil),                // 0: orcan.v1.ProductAssetPurpose
	(*ProductAsset)(nil),                       // 1: orcan.v1.ProductAsset
	(*ListProductAssetsRequest)(nil),           // 2: orcan.v1.ListProductAssetsRequest
	(*ListProductAssetsResponse)(nil),          // 3: orcan.v1.ListProductAssetsResponse
	(*GetProductAssetRequest)(nil),             // 4: orcan.v1.GetProductAssetRequest
	(*GetProductAssetResponse)(nil),            // 5: orcan.v1.GetProductAssetResponse
	(*GetProductAssetUploadURLRequest)(nil),    // 6: orcan.v1.GetProductAssetUploadURLRequest
	(*GetProductAssetUploadURLResponse)(nil),   // 7: orcan.v1.GetProductAssetUploadURLResponse
	(*ConfirmProductAssetUploadRequest)(nil),   // 8: orcan.v1.ConfirmProductAssetUploadRequest
	(*ConfirmProductAssetUploadResponse)(nil),  // 9: orcan.v1.ConfirmProductAssetUploadResponse
	(*DeleteProductAssetRequest)(nil),          // 10: orcan.v1.DeleteProductAssetRequest
	(*DeleteProductAssetResponse)(nil),         // 11: orcan.v1.DeleteProductAssetResponse
	(*GetProductAssetDownloadURLRequest)(nil),  // 12: orcan.v1.GetProductAssetDownloadURLRequest
	(*GetProductAssetDownloadURLResponse)(nil), // 13: orcan.v1.GetProductAssetDownloadURLResponse
	(*timestamppb.Timestamp)(nil),              // 14: google.protobuf.Timestamp
}
var file_orcan_v1_product_asset_proto_depIdxs = []int32{
	0,  // 0: orcan.v1.ProductAsset.purpose:type_name -> orcan.v1.ProductAssetPurpose
	14, // 1: orcan.v1.ProductAsset.created_at:type_name -> google.protobuf.Timestamp
	14, // 2: orcan.v1.ProductAsset.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: orcan.v1.ListProductAssetsResponse.assets:type_name -> orcan.v1.ProductAsset
	1,  // 4: orcan.v1.GetProductAssetResponse.asset:type_name -> orcan.v1.ProductAsset
	14, // 5: orcan.v1.GetProductAssetUploadURLResponse.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 6: orcan.v1.ConfirmProductAssetUploadResponse.asset:type_name -> orcan.v1.ProductAsset
	14, // 7: orcan.v1.GetProductAssetDownloadURLResponse.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 8: orcan.v1.ProductAssetService.ListProductAssets:input_type -> orcan.v1.ListProductAssetsRequest
	4,  // 9: orcan.v1.ProductAssetService.GetProductAsset:input_type -> orcan.v1.GetProductAssetRequest
	6,  // 10: orcan.v1.ProductAssetService.GetProductAssetUploadURL:input_type -> orcan.v1.GetProductAssetUploadURLRequest
	8,  // 11: orcan.v1.ProductAssetService.ConfirmProductAssetUpload:input_type -> orcan.v1.ConfirmProductAssetUploadRequest
	10, // 12: orcan.v1.ProductAssetService.DeleteProductAsset:input_type -> orcan.v1.DeleteProductAssetRequest
	12, // 13: orcan.v1.ProductAssetService.GetProductAssetDownloadURL:input_type -> orcan.v1.GetProductAssetDownloadURLRequest
	3,  // 14: orcan.v1.ProductAssetService.ListProductAssets:output_type -> orcan.v1.ListProductAssetsResponse
	5,  // 15: orcan.v1.ProductAssetService.GetProductAsset:output_type -> orcan.v1.GetProductAssetResponse
	7,  // 16: orcan.v1.ProductAssetService.GetProductAssetUploadURL:output_type -> orcan.v1.GetProductAssetUploadURLResponse
	9,  // 17: orcan.v1.ProductAssetService.ConfirmProductAssetUpload:output_type -> orcan.v1.ConfirmProductAssetUploadResponse
	11, // 18: orcan.v1.ProductAssetService.DeleteProductAsset:output_type -> orcan.v1.DeleteProductAssetResponse
	13, // 19: orcan.v1.ProductAssetService.GetProductAssetDownloadURL:output_type -> orcan.v1.GetProductAssetDownloadURLResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_orcan_v1_product_asset_proto_init() }
func file_orcan_v1_product_asset_proto_init() {
	if File_orcan_v1_product_asset_proto != nil {
		return
	}
	file_orcan_v1_product_asset_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orcan_v1_product_asset_proto_rawDesc), len(file_orcan_v1_product_asset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orcan_v1_product_asset_proto_goTypes,
		DependencyIndexes: file_orcan_v1_product_asset_proto_depIdxs,
		MessageInfos:      file_orcan_v1_product_asset_proto_msgTypes,
	}.Build()
	File_orcan_v1_product_asset_proto = out.File
	file_orcan_v1_product_asset_proto_goTypes = nil
	file_orcan_v1_product_asset_proto_depIdxs = nil
}
