// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: orcan/v1/product_inventory.proto

package orcanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductInventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     uint32                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Reserved      int32                  `protobuf:"varint,4,opt,name=reserved,proto3" json:"reserved,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductInventory) Reset() {
	*x = ProductInventory{}
	mi := &file_orcan_v1_product_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductInventory) ProtoMessage() {}

func (x *ProductInventory) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductInventory.ProtoReflect.Descriptor instead.
func (*ProductInventory) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *ProductInventory) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductInventory) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductInventory) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ProductInventory) GetReserved() int32 {
	if x != nil {
		return x.Reserved
	}
	return 0
}

func (x *ProductInventory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductInventory) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListProductInventoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductInventoriesRequest) Reset() {
	*x = ListProductInventoriesRequest{}
	mi := &file_orcan_v1_product_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductInventoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductInventoriesRequest) ProtoMessage() {}

func (x *ListProductInventoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductInventoriesRequest.ProtoReflect.Descriptor instead.
func (*ListProductInventoriesRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_inventory_proto_rawDescGZIP(), []int{1}
}

type ListProductInventoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventories   []*ProductInventory    `protobuf:"bytes,1,rep,name=inventories,proto3" json:"inventories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductInventoriesResponse) Reset() {
	*x = ListProductInventoriesResponse{}
	mi := &file_orcan_v1_product_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductInventoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductInventoriesResponse) ProtoMessage() {}

func (x *ListProductInventoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductInventoriesResponse.ProtoReflect.Descriptor instead.
func (*ListProductInventoriesResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *ListProductInventoriesResponse) GetInventories() []*ProductInventory {
	if x != nil {
		return x.Inventories
	}
	return nil
}

type GetProductInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductInventoryRequest) Reset() {
	*x = GetProductInventoryRequest{}
	mi := &file_orcan_v1_product_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductInventoryRequest) ProtoMessage() {}

func (x *GetProductInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductInventoryRequest.ProtoReflect.Descriptor instead.
func (*GetProductInventoryRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductInventoryRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProductInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     *ProductInventory      `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductInventoryResponse) Reset() {
	*x = GetProductInventoryResponse{}
	mi := &file_orcan_v1_product_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductInventoryResponse) ProtoMessage() {}

func (x *GetProductInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductInventoryResponse.ProtoReflect.Descriptor instead.
func (*GetProductInventoryResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductInventoryResponse) GetInventory() *ProductInventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type CreateProductInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Reserved      int32                  `protobuf:"varint,3,opt,name=reserved,proto3" json:"reserved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductInventoryRequest) Reset() {
	*x = CreateProductInventoryRequest{}
	mi := &file_orcan_v1_product_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductInventoryRequest) ProtoMessage() {}

func (x *CreateProductInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductInventoryRequest.ProtoReflect.Descriptor instead.
func (*CreateProductInventoryRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *CreateProductInventoryRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateProductInventoryRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateProductInventoryRequest) GetReserved() int32 {
	if x != nil {
		return x.Reserved
	}
	return 0
}

type CreateProductInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     *ProductInventory      `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductInventoryResponse) Reset() {
	*x = CreateProductInventoryResponse{}
	mi := &file_orcan_v1_product_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductInventoryResponse) ProtoMessage() {}

func (x *CreateProductInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductInventoryResponse.ProtoReflect.Descriptor instead.
func (*CreateProductInventoryResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *CreateProductInventoryResponse) GetInventory() *ProductInventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type UpdateProductInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     uint32                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Reserved      int32                  `protobuf:"varint,4,opt,name=reserved,proto3" json:"reserved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductInventoryRequest) Reset() {
	*x = UpdateProductInventoryRequest{}
	mi := &file_orcan_v1_product_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductInventoryRequest) ProtoMessage() {}

func (x *UpdateProductInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductInventoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductInventoryRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProductInventoryRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductInventoryRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateProductInventoryRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UpdateProductInventoryRequest) GetReserved() int32 {
	if x != nil {
		return x.Reserved
	}
	return 0
}

type UpdateProductInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     *ProductInventory      `protobuf:"bytes,1,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductInventoryResponse) Reset() {
	*x = UpdateProductInventoryResponse{}
	mi := &file_orcan_v1_product_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductInventoryResponse) ProtoMessage() {}

func (x *UpdateProductInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductInventoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductInventoryResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProductInventoryResponse) GetInventory() *ProductInventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type DeleteProductInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductInventoryRequest) Reset() {
	*x = DeleteProductInventoryRequest{}
	mi := &file_orcan_v1_product_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductInventoryRequest) ProtoMessage() {}

func (x *DeleteProductInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductInventoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductInventoryRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteProductInventoryRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteProductInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductInventoryResponse) Reset() {
	*x = DeleteProductInventoryResponse{}
	mi := &file_orcan_v1_product_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductInventoryResponse) ProtoMessage() {}

func (x *DeleteProductInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductInventoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductInventoryResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_inventory_proto_rawDescGZIP(), []int{10}
}

var File_orcan_v1_product_inventory_proto protoreflect.FileDescriptor

const file_orcan_v1_product_inventory_proto_rawDesc = "" +
	"\n" +
	" orcan/v1/product_inventory.proto\x12\borcan.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xef\x01\n" +
	"\x10ProductInventory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\rR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x1a\n" +
	"\breserved\x18\x04 \x01(\x05R\breserved\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x1f\n" +
	"\x1dListProductInventoriesRequest\"^\n" +
	"\x1eListProductInventoriesResponse\x12<\n" +
	"\vinventories\x18\x01 \x03(\v2\x1a.orcan.v1.ProductInventoryR\vinventories\",\n" +
	"\x1aGetProductInventoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"W\n" +
	"\x1bGetProductInventoryResponse\x128\n" +
	"\tinventory\x18\x01 \x01(\v2\x1a.orcan.v1.ProductInventoryR\tinventory\"v\n" +
	"\x1dCreateProductInventoryRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x1a\n" +
	"\breserved\x18\x03 \x01(\x05R\breserved\"Z\n" +
	"\x1eCreateProductInventoryResponse\x128\n" +
	"\tinventory\x18\x01 \x01(\v2\x1a.orcan.v1.ProductInventoryR\tinventory\"\x86\x01\n" +
	"\x1dUpdateProductInventoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\rR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x1a\n" +
	"\breserved\x18\x04 \x01(\x05R\breserved\"Z\n" +
	"\x1eUpdateProductInventoryResponse\x128\n" +
	"\tinventory\x18\x01 \x01(\v2\x1a.orcan.v1.ProductInventoryR\tinventory\"/\n" +
	"\x1dDeleteProductInventoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\" \n" +
	"\x1eDeleteProductInventoryResponse2\xb1\x04\n" +
	"\x17ProductInventoryService\x12k\n" +
	"\x16ListProductInventories\x12'.orcan.v1.ListProductInventoriesRequest\x1a(.orcan.v1.ListProductInventoriesResponse\x12b\n" +
	"\x13GetProductInventory\x12$.orcan.v1.GetProductInventoryRequest\x1a%.orcan.v1.GetProductInventoryResponse\x12k\n" +
	"\x16CreateProductInventory\x12'.orcan.v1.CreateProductInventoryRequest\x1a(.orcan.v1.CreateProductInventoryResponse\x12k\n" +
	"\x16UpdateProductInventory\x12'.orcan.v1.UpdateProductInventoryRequest\x1a(.orcan.v1.UpdateProductInventoryResponse\x12k\n" +
	"\x16DeleteProductInventory\x12'.orcan.v1.DeleteProductInventoryRequest\x1a(.orcan.v1.DeleteProductInventoryResponseBQZOgithub.com/asamigentoku/PinguCoin/server/orcan-api/internal/pb/orcan/v1;orcanv1b\x06proto3"

var (
	file_orcan_v1_product_inventory_proto_rawDescOnce sync.Once
	file_orcan_v1_product_inventory_proto_rawDescData []byte
)

func file_orcan_v1_product_inventory_proto_rawDescGZIP() []byte {
	file_orcan_v1_product_inventory_proto_rawDescOnce.Do(func() {
		file_orcan_v1_product_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orcan_v1_product_inventory_proto_rawDesc), len(file_orcan_v1_product_inventory_proto_rawDesc)))
	})
	return file_orcan_v1_product_inventory_proto_rawDescData
}

var file_orcan_v1_product_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_orcan_v1_product_inventory_proto_goTypes = []any{
	(*ProductInventory)(nil),               // 0: orcan.v1.ProductInventory
	(*ListProductInventoriesRequest)(nil),  // 1: orcan.v1.ListProductInventoriesRequest
	(*ListProductInventoriesResponse)(nil), // 2: orcan.v1.ListProductInventoriesResponse
	(*GetProductInventoryRequest)(nil),     // 3: orcan.v1.GetProductInventoryRequest
	(*GetProductInventoryResponse)(nil),    // 4: orcan.v1.GetProductInventoryResponse
	(*CreateProductInventoryRequest)(nil),  // 5: orcan.v1.CreateProductInventoryRequest
	(*CreateProductInventoryResponse)(nil), // 6: orcan.v1.CreateProductInventoryResponse
	(*UpdateProductInventoryRequest)(nil),  // 7: orcan.v1.UpdateProductInventoryRequest
	(*UpdateProductInventoryResponse)(nil), // 8: orcan.v1.UpdateProductInventoryResponse
	(*DeleteProductInventoryRequest)(nil),  // 9: orcan.v1.DeleteProductInventoryRequest
	(*DeleteProductInventoryResponse)(nil), // 10: orcan.v1.DeleteProductInventoryResponse
	(*timestamppb.Timestamp)(nil),          // 11: google.protobuf.Timestamp
}
var file_orcan_v1_product_inventory_proto_depIdxs = []int32{
	11, // 0: orcan.v1.ProductInventory.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: orcan.v1.ProductInventory.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: orcan.v1.ListProductInventoriesResponse.inventories:type_name -> orcan.v1.ProductInventory
	0,  // 3: orcan.v1.GetProductInventoryResponse.inventory:type_name -> orcan.v1.ProductInventory
	0,  // 4: orcan.v1.CreateProductInventoryResponse.inventory:type_name -> orcan.v1.ProductInventory
	0,  // 5: orcan.v1.UpdateProductInventoryResponse.inventory:type_name -> orcan.v1.ProductInventory
	1,  // 6: orcan.v1.ProductInventoryService.ListProductInventories:input_type -> orcan.v1.ListProductInventoriesRequest
	3,  // 7: orcan.v1.ProductInventoryService.GetProductInventory:input_type -> orcan.v1.GetProductInventoryRequest
	5,  // 8: orcan.v1.ProductInventoryService.CreateProductInventory:input_type -> orcan.v1.CreateProductInventoryRequest
	7,  // 9: orcan.v1.ProductInventoryService.UpdateProductInventory:input_type -> orcan.v1.UpdateProductInventoryRequest
	9,  // 10: orcan.v1.ProductInventoryService.DeleteProductInventory:input_type -> orcan.v1.DeleteProductInventoryRequest
	2,  // 11: orcan.v1.ProductInventoryService.ListProductInventories:output_type -> orcan.v1.ListProductInventoriesResponse
	4,  // 12: orcan.v1.ProductInventoryService.GetProductInventory:output_type -> orcan.v1.GetProductInventoryResponse
	6,  // 13: orcan.v1.ProductInventoryService.CreateProductInventory:output_type -> orcan.v1.CreateProductInventoryResponse
	8,  // 14: orcan.v1.ProductInventoryService.UpdateProductInventory:output_type -> orcan.v1.UpdateProductInventoryResponse
	10, // 15: orcan.v1.ProductInventoryService.DeleteProductInventory:output_type -> orcan.v1.DeleteProductInventoryResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_orcan_v1_product_inventory_proto_init() }
func file_orcan_v1_product_inventory_proto_init() {
	if File_orcan_v1_product_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orcan_v1_product_inventory_proto_rawDesc), len(file_orcan_v1_product_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orcan_v1_product_inventory_proto_goTypes,
		DependencyIndexes: file_orcan_v1_product_inventory_proto_depIdxs,
		MessageInfos:      file_orcan_v1_product_inventory_proto_msgTypes,
	}.Build()
	File_orcan_v1_product_inventory_proto = out.File
	file_orcan_v1_product_inventory_proto_goTypes = nil
	file_orcan_v1_product_inventory_proto_depIdxs = nil
}
