// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: orcan/v1/product_listing.proto

package orcanv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductListingService_ListProductListings_FullMethodName  = "/orcan.v1.ProductListingService/ListProductListings"
	ProductListingService_GetProductListing_FullMethodName    = "/orcan.v1.ProductListingService/GetProductListing"
	ProductListingService_CreateProductListing_FullMethodName = "/orcan.v1.ProductListingService/CreateProductListing"
	ProductListingService_UpdateProductListing_FullMethodName = "/orcan.v1.ProductListingService/UpdateProductListing"
	ProductListingService_DeleteProductListing_FullMethodName = "/orcan.v1.ProductListingService/DeleteProductListing"
)

// ProductListingServiceClient is the client API for ProductListingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductListingServiceClient interface {
	ListProductListings(ctx context.Context, in *ListProductListingsRequest, opts ...grpc.CallOption) (*ListProductListingsResponse, error)
	GetProductListing(ctx context.Context, in *GetProductListingRequest, opts ...grpc.CallOption) (*GetProductListingResponse, error)
	CreateProductListing(ctx context.Context, in *CreateProductListingRequest, opts ...grpc.CallOption) (*CreateProductListingResponse, error)
	UpdateProductListing(ctx context.Context, in *UpdateProductListingRequest, opts ...grpc.CallOption) (*UpdateProductListingResponse, error)
	DeleteProductListing(ctx context.Context, in *DeleteProductListingRequest, opts ...grpc.CallOption) (*DeleteProductListingResponse, error)
}

type productListingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductListingServiceClient(cc grpc.ClientConnInterface) ProductListingServiceClient {
	return &productListingServiceClient{cc}
}

func (c *productListingServiceClient) ListProductListings(ctx context.Context, in *ListProductListingsRequest, opts ...grpc.CallOption) (*ListProductListingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductListingsResponse)
	err := c.cc.Invoke(ctx, ProductListingService_ListProductListings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productListingServiceClient) GetProductListing(ctx context.Context, in *GetProductListingRequest, opts ...grpc.CallOption) (*GetProductListingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductListingResponse)
	err := c.cc.Invoke(ctx, ProductListingService_GetProductListing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productListingServiceClient) CreateProductListing(ctx context.Context, in *CreateProductListingRequest, opts ...grpc.CallOption) (*CreateProductListingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProductListingResponse)
	err := c.cc.Invoke(ctx, ProductListingService_CreateProductListing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productListingServiceClient) UpdateProductListing(ctx context.Context, in *UpdateProductListingRequest, opts ...grpc.CallOption) (*UpdateProductListingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProductListingResponse)
	err := c.cc.Invoke(ctx, ProductListingService_UpdateProductListing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productListingServiceClient) DeleteProductListing(ctx context.Context, in *DeleteProductListingRequest, opts ...grpc.CallOption) (*DeleteProductListingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProductListingResponse)
	err := c.cc.Invoke(ctx, ProductListingService_DeleteProductListing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductListingServiceServer is the server API for ProductListingService service.
// All implementations must embed UnimplementedProductListingServiceServer
// for forward compatibility.
type ProductListingServiceServer interface {
	ListProductListings(context.Context, *ListProductListingsRequest) (*ListProductListingsResponse, error)
	GetProductListing(context.Context, *GetProductListingRequest) (*GetProductListingResponse, error)
	CreateProductListing(context.Context, *CreateProductListingRequest) (*CreateProductListingResponse, error)
	UpdateProductListing(context.Context, *UpdateProductListingRequest) (*UpdateProductListingResponse, error)
	DeleteProductListing(context.Context, *DeleteProductListingRequest) (*DeleteProductListingResponse, error)
	mustEmbedUnimplementedProductListingServiceServer()
}

// UnimplementedProductListingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductListingServiceServer struct{}

func (UnimplementedProductListingServiceServer) ListProductListings(context.Context, *ListProductListingsRequest) (*ListProductListingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProductListings not implemented")
}
func (UnimplementedProductListingServiceServer) GetProductListing(context.Context, *GetProductListingRequest) (*GetProductListingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductListing not implemented")
}
func (UnimplementedProductListingServiceServer) CreateProductListing(context.Context, *CreateProductListingRequest) (*CreateProductListingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProductListing not implemented")
}
func (UnimplementedProductListingServiceServer) UpdateProductListing(context.Context, *UpdateProductListingRequest) (*UpdateProductListingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProductListing not implemented")
}
func (UnimplementedProductListingServiceServer) DeleteProductListing(context.Context, *DeleteProductListingRequest) (*DeleteProductListingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProductListing not implemented")
}
func (UnimplementedProductListingServiceServer) mustEmbedUnimplementedProductListingServiceServer() {}
func (UnimplementedProductListingServiceServer) testEmbeddedByValue()                               {}

// UnsafeProductListingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductListingServiceServer will
// result in compilation errors.
type UnsafeProductListingServiceServer interface {
	mustEmbedUnimplementedProductListingServiceServer()
}

func RegisterProductListingServiceServer(s grpc.ServiceRegistrar, srv ProductListingServiceServer) {
	// If the following call panics, it indicates UnimplementedProductListingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductListingService_ServiceDesc, srv)
}

func _ProductListingService_ListProductListings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductListingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductListingServiceServer).ListProductListings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductListingService_ListProductListings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductListingServiceServer).ListProductListings(ctx, req.(*ListProductListingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductListingService_GetProductListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductListingServiceServer).GetProductListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductListingService_GetProductListing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductListingServiceServer).GetProductListing(ctx, req.(*GetProductListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductListingService_CreateProductListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductListingServiceServer).CreateProductListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductListingService_CreateProductListing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductListingServiceServer).CreateProductListing(ctx, req.(*CreateProductListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductListingService_UpdateProductListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductListingServiceServer).UpdateProductListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductListingService_UpdateProductListing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductListingServiceServer).UpdateProductListing(ctx, req.(*UpdateProductListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductListingService_DeleteProductListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductListingServiceServer).DeleteProductListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductListingService_DeleteProductListing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductListingServiceServer).DeleteProductListing(ctx, req.(*DeleteProductListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductListingService_ServiceDesc is the grpc.ServiceDesc for ProductListingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductListingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orcan.v1.ProductListingService",
	HandlerType: (*ProductListingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProductListings",
			Handler:    _ProductListingService_ListProductListings_Handler,
		},
		{
			MethodName: "GetProductListing",
			Handler:    _ProductListingService_GetProductListing_Handler,
		},
		{
			MethodName: "CreateProductListing",
			Handler:    _ProductListingService_CreateProductListing_Handler,
		},
		{
			MethodName: "UpdateProductListing",
			Handler:    _ProductListingService_UpdateProductListing_Handler,
		},
		{
			MethodName: "DeleteProductListing",
			Handler:    _ProductListingService_DeleteProductListing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orcan/v1/product_listing.proto",
}
