// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: orcan/v1/user.proto

package orcanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User はサービス利用者を表す。認証はClerk(フロントエンド)が担い、orcan-apiはパスワード等の
// 認証情報を一切保持しない。clerk_user_id でClerkのユーザーと1:1に対応する、アプリ内プロフィールのみ。
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClerkUserId   string                 `protobuf:"bytes,2,opt,name=clerk_user_id,json=clerkUserId,proto3" json:"clerk_user_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_orcan_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_orcan_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetClerkUserId() string {
	if x != nil {
		return x.ClerkUserId
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_orcan_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_user_proto_rawDescGZIP(), []int{1}
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_orcan_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_orcan_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_orcan_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserByClerkIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClerkUserId   string                 `protobuf:"bytes,1,opt,name=clerk_user_id,json=clerkUserId,proto3" json:"clerk_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByClerkIDRequest) Reset() {
	*x = GetUserByClerkIDRequest{}
	mi := &file_orcan_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByClerkIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByClerkIDRequest) ProtoMessage() {}

func (x *GetUserByClerkIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByClerkIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserByClerkIDRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserByClerkIDRequest) GetClerkUserId() string {
	if x != nil {
		return x.ClerkUserId
	}
	return ""
}

type GetUserByClerkIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByClerkIDResponse) Reset() {
	*x = GetUserByClerkIDResponse{}
	mi := &file_orcan_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByClerkIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByClerkIDResponse) ProtoMessage() {}

func (x *GetUserByClerkIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByClerkIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserByClerkIDResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserByClerkIDResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type EnsureUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClerkUserId   string                 `protobuf:"bytes,1,opt,name=clerk_user_id,json=clerkUserId,proto3" json:"clerk_user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureUserRequest) Reset() {
	*x = EnsureUserRequest{}
	mi := &file_orcan_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureUserRequest) ProtoMessage() {}

func (x *EnsureUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureUserRequest.ProtoReflect.Descriptor instead.
func (*EnsureUserRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *EnsureUserRequest) GetClerkUserId() string {
	if x != nil {
		return x.ClerkUserId
	}
	return ""
}

func (x *EnsureUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EnsureUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EnsureUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureUserResponse) Reset() {
	*x = EnsureUserResponse{}
	mi := &file_orcan_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureUserResponse) ProtoMessage() {}

func (x *EnsureUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureUserResponse.ProtoReflect.Descriptor instead.
func (*EnsureUserResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *EnsureUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// UpdateUserRequest は氏名の更新のみ扱う(emailはClerk側が真実の記録を持つため今回のスコープ外)。
type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_orcan_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateUserRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_orcan_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_orcan_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteUserRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_orcan_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_user_proto_rawDescGZIP(), []int{12}
}

var File_orcan_v1_user_proto protoreflect.FileDescriptor

const file_orcan_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x13orcan/v1/user.proto\x12\borcan.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xda\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\"\n" +
	"\rclerk_user_id\x18\x02 \x01(\tR\vclerkUserId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x12\n" +
	"\x10ListUsersRequest\"9\n" +
	"\x11ListUsersResponse\x12$\n" +
	"\x05users\x18\x01 \x03(\v2\x0e.orcan.v1.UserR\x05users\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"5\n" +
	"\x0fGetUserResponse\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.orcan.v1.UserR\x04user\"=\n" +
	"\x17GetUserByClerkIDRequest\x12\"\n" +
	"\rclerk_user_id\x18\x01 \x01(\tR\vclerkUserId\">\n" +
	"\x18GetUserByClerkIDResponse\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.orcan.v1.UserR\x04user\"a\n" +
	"\x11EnsureUserRequest\x12\"\n" +
	"\rclerk_user_id\x18\x01 \x01(\tR\vclerkUserId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"8\n" +
	"\x12EnsureUserResponse\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.orcan.v1.UserR\x04user\"7\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"8\n" +
	"\x12UpdateUserResponse\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.orcan.v1.UserR\x04user\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x14\n" +
	"\x12DeleteUserResponse2\xc9\x03\n" +
	"\vUserService\x12D\n" +
	"\tListUsers\x12\x1a.orcan.v1.ListUsersRequest\x1a\x1b.orcan.v1.ListUsersResponse\x12>\n" +
	"\aGetUser\x12\x18.orcan.v1.GetUserRequest\x1a\x19.orcan.v1.GetUserResponse\x12Y\n" +
	"\x10GetUserByClerkID\x12!.orcan.v1.GetUserByClerkIDRequest\x1a\".orcan.v1.GetUserByClerkIDResponse\x12G\n" +
	"\n" +
	"EnsureUser\x12\x1b.orcan.v1.EnsureUserRequest\x1a\x1c.orcan.v1.EnsureUserResponse\x12G\n" +
	"\n" +
	"UpdateUser\x12\x1b.orcan.v1.UpdateUserRequest\x1a\x1c.orcan.v1.UpdateUserResponse\x12G\n" +
	"\n" +
	"DeleteUser\x12\x1b.orcan.v1.DeleteUserRequest\x1a\x1c.orcan.v1.DeleteUserResponseBQZOgithub.com/asamigentoku/PinguCoin/server/orcan-api/internal/pb/orcan/v1;orcanv1b\x06proto3"

var (
	file_orcan_v1_user_proto_rawDescOnce sync.Once
	file_orcan_v1_user_proto_rawDescData []byte
)

func file_orcan_v1_user_proto_rawDescGZIP() []byte {
	file_orcan_v1_user_proto_rawDescOnce.Do(func() {
		file_orcan_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orcan_v1_user_proto_rawDesc), len(file_orcan_v1_user_proto_rawDesc)))
	})
	return file_orcan_v1_user_proto_rawDescData
}

var file_orcan_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_orcan_v1_user_proto_goTypes = []any{
	(*User)(nil),                     // 0: orcan.v1.User
	(*ListUsersRequest)(nil),         // 1: orcan.v1.ListUsersRequest
	(*ListUsersResponse)(nil),        // 2: orcan.v1.ListUsersResponse
	(*GetUserRequest)(nil),           // 3: orcan.v1.GetUserRequest
	(*GetUserResponse)(nil),          // 4: orcan.v1.GetUserResponse
	(*GetUserByClerkIDRequest)(nil),  // 5: orcan.v1.GetUserByClerkIDRequest
	(*GetUserByClerkIDResponse)(nil), // 6: orcan.v1.GetUserByClerkIDResponse
	(*EnsureUserRequest)(nil),        // 7: orcan.v1.EnsureUserRequest
	(*EnsureUserResponse)(nil),       // 8: orcan.v1.EnsureUserResponse
	(*UpdateUserRequest)(nil),        // 9: orcan.v1.UpdateUserRequest
	(*UpdateUserResponse)(nil),       // 10: orcan.v1.UpdateUserResponse
	(*DeleteUserRequest)(nil),        // 11: orcan.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),       // 12: orcan.v1.DeleteUserResponse
	(*timestamppb.Timestamp)(nil),    // 13: google.protobuf.Timestamp
}
var file_orcan_v1_user_proto_depIdxs = []int32{
	13, // 0: orcan.v1.User.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: orcan.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: orcan.v1.ListUsersResponse.users:type_name -> orcan.v1.User
	0,  // 3: orcan.v1.GetUserResponse.user:type_name -> orcan.v1.User
	0,  // 4: orcan.v1.GetUserByClerkIDResponse.user:type_name -> orcan.v1.User
	0,  // 5: orcan.v1.EnsureUserResponse.user:type_name -> orcan.v1.User
	0,  // 6: orcan.v1.UpdateUserResponse.user:type_name -> orcan.v1.User
	1,  // 7: orcan.v1.UserService.ListUsers:input_type -> orcan.v1.ListUsersRequest
	3,  // 8: orcan.v1.UserService.GetUser:input_type -> orcan.v1.GetUserRequest
	5,  // 9: orcan.v1.UserService.GetUserByClerkID:input_type -> orcan.v1.GetUserByClerkIDRequest
	7,  // 10: orcan.v1.UserService.EnsureUser:input_type -> orcan.v1.EnsureUserRequest
	9,  // 11: orcan.v1.UserService.UpdateUser:input_type -> orcan.v1.UpdateUserRequest
	11, // 12: orcan.v1.UserService.DeleteUser:input_type -> orcan.v1.DeleteUserRequest
	2,  // 13: orcan.v1.UserService.ListUsers:output_type -> orcan.v1.ListUsersResponse
	4,  // 14: orcan.v1.UserService.GetUser:output_type -> orcan.v1.GetUserResponse
	6,  // 15: orcan.v1.UserService.GetUserByClerkID:output_type -> orcan.v1.GetUserByClerkIDResponse
	8,  // 16: orcan.v1.UserService.EnsureUser:output_type -> orcan.v1.EnsureUserResponse
	10, // 17: orcan.v1.UserService.UpdateUser:output_type -> orcan.v1.UpdateUserResponse
	12, // 18: orcan.v1.UserService.DeleteUser:output_type -> orcan.v1.DeleteUserResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_orcan_v1_user_proto_init() }
func file_orcan_v1_user_proto_init() {
	if File_orcan_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orcan_v1_user_proto_rawDesc), len(file_orcan_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orcan_v1_user_proto_goTypes,
		DependencyIndexes: file_orcan_v1_user_proto_depIdxs,
		MessageInfos:      file_orcan_v1_user_proto_msgTypes,
	}.Build()
	File_orcan_v1_user_proto = out.File
	file_orcan_v1_user_proto_goTypes = nil
	file_orcan_v1_user_proto_depIdxs = nil
}
