package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/asamigentoku/PinguCoin/server/pingu-api/graph/model"
	"github.com/asamigentoku/PinguCoin/server/pingu-api/internal/apperr"
	orcanpb "github.com/asamigentoku/PinguCoin/server/pingu-api/internal/pb/orcan/v1"
	"github.com/asamigentoku/PinguCoin/server/pingu-api/internal/reqcontext"
)

// CreateProduct is the resolver for the createProduct field.
func (resolver *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.Product, error) {
	response, err := resolver.Orcan.Product.CreateProduct(ctx, &orcanpb.CreateProductRequest{
		UserId:      uint32(input.UserID),
		CategoryId:  uint32(input.CategoryID),
		Name:        input.Name,
		Description: strOrEmpty(input.Description),
		ImageUrl:    strOrEmpty(input.ImageURL),
		Price:       int64(input.Price),
		Status:      strOrEmpty(input.Status),
	})
	if err != nil {
		return nil, apperr.FromGRPC(err)
	}
	return productFromPB(response.GetProduct()), nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (resolver *mutationResolver) UpdateProduct(ctx context.Context, id int32, input model.UpdateProductInput) (*model.Product, error) {
	response, err := resolver.Orcan.Product.UpdateProduct(ctx, &orcanpb.UpdateProductRequest{
		Id:          uint32(id),
		UserId:      uint32(input.UserID),
		CategoryId:  uint32(input.CategoryID),
		Name:        input.Name,
		Description: strOrEmpty(input.Description),
		ImageUrl:    strOrEmpty(input.ImageURL),
		Price:       int64(input.Price),
		Status:      strOrEmpty(input.Status),
	})
	if err != nil {
		return nil, apperr.FromGRPC(err)
	}
	return productFromPB(response.GetProduct()), nil
}

// DeleteProduct is the resolver for the deleteProduct field.
func (resolver *mutationResolver) DeleteProduct(ctx context.Context, id int32) (bool, error) {
	if _, err := resolver.Orcan.Product.DeleteProduct(ctx, &orcanpb.DeleteProductRequest{Id: uint32(id)}); err != nil {
		return false, apperr.FromGRPC(err)
	}
	return true, nil
}

// UpdateUser is the resolver for the updateUser field。ログイン中の本人のみ更新できる。
func (resolver *mutationResolver) UpdateUser(ctx context.Context, id int32, input model.UpdateUserInput) (*model.User, error) {
	claims, ok := reqcontext.UserFromContext(ctx)
	if !ok {
		return nil, apperr.Unauthenticated("login is required")
	}
	if claims.UserID != uint(id) {
		return nil, apperr.Unauthenticated("cannot update another user")
	}

	response, err := resolver.Orcan.User.UpdateUser(ctx, &orcanpb.UpdateUserRequest{
		Id:   uint32(id),
		Name: input.Name,
	})
	if err != nil {
		return nil, apperr.FromGRPC(err)
	}
	return userFromPB(response.GetUser()), nil
}

// Products is the resolver for the products field.
func (resolver *queryResolver) Products(ctx context.Context, userID *int32) ([]*model.Product, error) {
	request := &orcanpb.ListProductsRequest{}
	if userID != nil {
		userIDValue := uint32(*userID)
		request.UserId = &userIDValue
	}

	response, err := resolver.Orcan.Product.ListProducts(ctx, request)
	if err != nil {
		return nil, apperr.FromGRPC(err)
	}

	products := make([]*model.Product, 0, len(response.GetProducts()))
	for _, product := range response.GetProducts() {
		products = append(products, productFromPB(product))
	}
	return products, nil
}

// Product is the resolver for the product field.
func (resolver *queryResolver) Product(ctx context.Context, id int32) (*model.Product, error) {
	response, err := resolver.Orcan.Product.GetProduct(ctx, &orcanpb.GetProductRequest{Id: uint32(id)})
	if err != nil {
		return nil, apperr.FromGRPC(err)
	}
	return productFromPB(response.GetProduct()), nil
}

// Users is the resolver for the users field.
func (resolver *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	response, err := resolver.Orcan.User.ListUsers(ctx, &orcanpb.ListUsersRequest{})
	if err != nil {
		return nil, apperr.FromGRPC(err)
	}

	users := make([]*model.User, 0, len(response.GetUsers()))
	for _, user := range response.GetUsers() {
		users = append(users, userFromPB(user))
	}
	return users, nil
}

// User is the resolver for the user field.
func (resolver *queryResolver) User(ctx context.Context, id int32) (*model.User, error) {
	response, err := resolver.Orcan.User.GetUser(ctx, &orcanpb.GetUserRequest{Id: uint32(id)})
	if err != nil {
		return nil, apperr.FromGRPC(err)
	}
	return userFromPB(response.GetUser()), nil
}

// Me is the resolver for the me field.
func (resolver *queryResolver) Me(ctx context.Context) (*model.User, error) {
	claims, ok := reqcontext.UserFromContext(ctx)
	if !ok {
		return nil, apperr.Unauthenticated("login is required")
	}

	response, err := resolver.Orcan.User.GetUser(ctx, &orcanpb.GetUserRequest{Id: uint32(claims.UserID)})
	if err != nil {
		return nil, apperr.FromGRPC(err)
	}
	return userFromPB(response.GetUser()), nil
}

// Mutation returns MutationResolver implementation.
func (resolver *Resolver) Mutation() MutationResolver { return &mutationResolver{resolver} }

// Query returns QueryResolver implementation.
func (resolver *Resolver) Query() QueryResolver { return &queryResolver{resolver} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
