// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: orcan/v1/product_asset.proto

package orcanv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductAssetService_ListProductAssets_FullMethodName          = "/orcan.v1.ProductAssetService/ListProductAssets"
	ProductAssetService_GetProductAsset_FullMethodName            = "/orcan.v1.ProductAssetService/GetProductAsset"
	ProductAssetService_GetProductAssetUploadURL_FullMethodName   = "/orcan.v1.ProductAssetService/GetProductAssetUploadURL"
	ProductAssetService_ConfirmProductAssetUpload_FullMethodName  = "/orcan.v1.ProductAssetService/ConfirmProductAssetUpload"
	ProductAssetService_DeleteProductAsset_FullMethodName         = "/orcan.v1.ProductAssetService/DeleteProductAsset"
	ProductAssetService_GetProductAssetDownloadURL_FullMethodName = "/orcan.v1.ProductAssetService/GetProductAssetDownloadURL"
)

// ProductAssetServiceClient is the client API for ProductAssetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductAssetServiceClient interface {
	ListProductAssets(ctx context.Context, in *ListProductAssetsRequest, opts ...grpc.CallOption) (*ListProductAssetsResponse, error)
	GetProductAsset(ctx context.Context, in *GetProductAssetRequest, opts ...grpc.CallOption) (*GetProductAssetResponse, error)
	GetProductAssetUploadURL(ctx context.Context, in *GetProductAssetUploadURLRequest, opts ...grpc.CallOption) (*GetProductAssetUploadURLResponse, error)
	ConfirmProductAssetUpload(ctx context.Context, in *ConfirmProductAssetUploadRequest, opts ...grpc.CallOption) (*ConfirmProductAssetUploadResponse, error)
	DeleteProductAsset(ctx context.Context, in *DeleteProductAssetRequest, opts ...grpc.CallOption) (*DeleteProductAssetResponse, error)
	GetProductAssetDownloadURL(ctx context.Context, in *GetProductAssetDownloadURLRequest, opts ...grpc.CallOption) (*GetProductAssetDownloadURLResponse, error)
}

type productAssetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductAssetServiceClient(cc grpc.ClientConnInterface) ProductAssetServiceClient {
	return &productAssetServiceClient{cc}
}

func (c *productAssetServiceClient) ListProductAssets(ctx context.Context, in *ListProductAssetsRequest, opts ...grpc.CallOption) (*ListProductAssetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductAssetsResponse)
	err := c.cc.Invoke(ctx, ProductAssetService_ListProductAssets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productAssetServiceClient) GetProductAsset(ctx context.Context, in *GetProductAssetRequest, opts ...grpc.CallOption) (*GetProductAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductAssetResponse)
	err := c.cc.Invoke(ctx, ProductAssetService_GetProductAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productAssetServiceClient) GetProductAssetUploadURL(ctx context.Context, in *GetProductAssetUploadURLRequest, opts ...grpc.CallOption) (*GetProductAssetUploadURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductAssetUploadURLResponse)
	err := c.cc.Invoke(ctx, ProductAssetService_GetProductAssetUploadURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productAssetServiceClient) ConfirmProductAssetUpload(ctx context.Context, in *ConfirmProductAssetUploadRequest, opts ...grpc.CallOption) (*ConfirmProductAssetUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmProductAssetUploadResponse)
	err := c.cc.Invoke(ctx, ProductAssetService_ConfirmProductAssetUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productAssetServiceClient) DeleteProductAsset(ctx context.Context, in *DeleteProductAssetRequest, opts ...grpc.CallOption) (*DeleteProductAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProductAssetResponse)
	err := c.cc.Invoke(ctx, ProductAssetService_DeleteProductAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productAssetServiceClient) GetProductAssetDownloadURL(ctx context.Context, in *GetProductAssetDownloadURLRequest, opts ...grpc.CallOption) (*GetProductAssetDownloadURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductAssetDownloadURLResponse)
	err := c.cc.Invoke(ctx, ProductAssetService_GetProductAssetDownloadURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductAssetServiceServer is the server API for ProductAssetService service.
// All implementations must embed UnimplementedProductAssetServiceServer
// for forward compatibility.
type ProductAssetServiceServer interface {
	ListProductAssets(context.Context, *ListProductAssetsRequest) (*ListProductAssetsResponse, error)
	GetProductAsset(context.Context, *GetProductAssetRequest) (*GetProductAssetResponse, error)
	GetProductAssetUploadURL(context.Context, *GetProductAssetUploadURLRequest) (*GetProductAssetUploadURLResponse, error)
	ConfirmProductAssetUpload(context.Context, *ConfirmProductAssetUploadRequest) (*ConfirmProductAssetUploadResponse, error)
	DeleteProductAsset(context.Context, *DeleteProductAssetRequest) (*DeleteProductAssetResponse, error)
	GetProductAssetDownloadURL(context.Context, *GetProductAssetDownloadURLRequest) (*GetProductAssetDownloadURLResponse, error)
	mustEmbedUnimplementedProductAssetServiceServer()
}

// UnimplementedProductAssetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductAssetServiceServer struct{}

func (UnimplementedProductAssetServiceServer) ListProductAssets(context.Context, *ListProductAssetsRequest) (*ListProductAssetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProductAssets not implemented")
}
func (UnimplementedProductAssetServiceServer) GetProductAsset(context.Context, *GetProductAssetRequest) (*GetProductAssetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductAsset not implemented")
}
func (UnimplementedProductAssetServiceServer) GetProductAssetUploadURL(context.Context, *GetProductAssetUploadURLRequest) (*GetProductAssetUploadURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductAssetUploadURL not implemented")
}
func (UnimplementedProductAssetServiceServer) ConfirmProductAssetUpload(context.Context, *ConfirmProductAssetUploadRequest) (*ConfirmProductAssetUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmProductAssetUpload not implemented")
}
func (UnimplementedProductAssetServiceServer) DeleteProductAsset(context.Context, *DeleteProductAssetRequest) (*DeleteProductAssetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProductAsset not implemented")
}
func (UnimplementedProductAssetServiceServer) GetProductAssetDownloadURL(context.Context, *GetProductAssetDownloadURLRequest) (*GetProductAssetDownloadURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductAssetDownloadURL not implemented")
}
func (UnimplementedProductAssetServiceServer) mustEmbedUnimplementedProductAssetServiceServer() {}
func (UnimplementedProductAssetServiceServer) testEmbeddedByValue()                             {}

// UnsafeProductAssetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductAssetServiceServer will
// result in compilation errors.
type UnsafeProductAssetServiceServer interface {
	mustEmbedUnimplementedProductAssetServiceServer()
}

func RegisterProductAssetServiceServer(s grpc.ServiceRegistrar, srv ProductAssetServiceServer) {
	// If the following call panics, it indicates UnimplementedProductAssetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductAssetService_ServiceDesc, srv)
}

func _ProductAssetService_ListProductAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductAssetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductAssetServiceServer).ListProductAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductAssetService_ListProductAssets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductAssetServiceServer).ListProductAssets(ctx, req.(*ListProductAssetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductAssetService_GetProductAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductAssetServiceServer).GetProductAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductAssetService_GetProductAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductAssetServiceServer).GetProductAsset(ctx, req.(*GetProductAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductAssetService_GetProductAssetUploadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductAssetUploadURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductAssetServiceServer).GetProductAssetUploadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductAssetService_GetProductAssetUploadURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductAssetServiceServer).GetProductAssetUploadURL(ctx, req.(*GetProductAssetUploadURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductAssetService_ConfirmProductAssetUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmProductAssetUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductAssetServiceServer).ConfirmProductAssetUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductAssetService_ConfirmProductAssetUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductAssetServiceServer).ConfirmProductAssetUpload(ctx, req.(*ConfirmProductAssetUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductAssetService_DeleteProductAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductAssetServiceServer).DeleteProductAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductAssetService_DeleteProductAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductAssetServiceServer).DeleteProductAsset(ctx, req.(*DeleteProductAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductAssetService_GetProductAssetDownloadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductAssetDownloadURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductAssetServiceServer).GetProductAssetDownloadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductAssetService_GetProductAssetDownloadURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductAssetServiceServer).GetProductAssetDownloadURL(ctx, req.(*GetProductAssetDownloadURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductAssetService_ServiceDesc is the grpc.ServiceDesc for ProductAssetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductAssetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orcan.v1.ProductAssetService",
	HandlerType: (*ProductAssetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProductAssets",
			Handler:    _ProductAssetService_ListProductAssets_Handler,
		},
		{
			MethodName: "GetProductAsset",
			Handler:    _ProductAssetService_GetProductAsset_Handler,
		},
		{
			MethodName: "GetProductAssetUploadURL",
			Handler:    _ProductAssetService_GetProductAssetUploadURL_Handler,
		},
		{
			MethodName: "ConfirmProductAssetUpload",
			Handler:    _ProductAssetService_ConfirmProductAssetUpload_Handler,
		},
		{
			MethodName: "DeleteProductAsset",
			Handler:    _ProductAssetService_DeleteProductAsset_Handler,
		},
		{
			MethodName: "GetProductAssetDownloadURL",
			Handler:    _ProductAssetService_GetProductAssetDownloadURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orcan/v1/product_asset.proto",
}
