// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: orcan/v1/product_detail.proto

package orcanv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductDetailService_ListProductDetails_FullMethodName  = "/orcan.v1.ProductDetailService/ListProductDetails"
	ProductDetailService_GetProductDetail_FullMethodName    = "/orcan.v1.ProductDetailService/GetProductDetail"
	ProductDetailService_CreateProductDetail_FullMethodName = "/orcan.v1.ProductDetailService/CreateProductDetail"
	ProductDetailService_UpdateProductDetail_FullMethodName = "/orcan.v1.ProductDetailService/UpdateProductDetail"
	ProductDetailService_DeleteProductDetail_FullMethodName = "/orcan.v1.ProductDetailService/DeleteProductDetail"
)

// ProductDetailServiceClient is the client API for ProductDetailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductDetailServiceClient interface {
	ListProductDetails(ctx context.Context, in *ListProductDetailsRequest, opts ...grpc.CallOption) (*ListProductDetailsResponse, error)
	GetProductDetail(ctx context.Context, in *GetProductDetailRequest, opts ...grpc.CallOption) (*GetProductDetailResponse, error)
	CreateProductDetail(ctx context.Context, in *CreateProductDetailRequest, opts ...grpc.CallOption) (*CreateProductDetailResponse, error)
	UpdateProductDetail(ctx context.Context, in *UpdateProductDetailRequest, opts ...grpc.CallOption) (*UpdateProductDetailResponse, error)
	DeleteProductDetail(ctx context.Context, in *DeleteProductDetailRequest, opts ...grpc.CallOption) (*DeleteProductDetailResponse, error)
}

type productDetailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductDetailServiceClient(cc grpc.ClientConnInterface) ProductDetailServiceClient {
	return &productDetailServiceClient{cc}
}

func (c *productDetailServiceClient) ListProductDetails(ctx context.Context, in *ListProductDetailsRequest, opts ...grpc.CallOption) (*ListProductDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductDetailsResponse)
	err := c.cc.Invoke(ctx, ProductDetailService_ListProductDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productDetailServiceClient) GetProductDetail(ctx context.Context, in *GetProductDetailRequest, opts ...grpc.CallOption) (*GetProductDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductDetailResponse)
	err := c.cc.Invoke(ctx, ProductDetailService_GetProductDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productDetailServiceClient) CreateProductDetail(ctx context.Context, in *CreateProductDetailRequest, opts ...grpc.CallOption) (*CreateProductDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProductDetailResponse)
	err := c.cc.Invoke(ctx, ProductDetailService_CreateProductDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productDetailServiceClient) UpdateProductDetail(ctx context.Context, in *UpdateProductDetailRequest, opts ...grpc.CallOption) (*UpdateProductDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProductDetailResponse)
	err := c.cc.Invoke(ctx, ProductDetailService_UpdateProductDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productDetailServiceClient) DeleteProductDetail(ctx context.Context, in *DeleteProductDetailRequest, opts ...grpc.CallOption) (*DeleteProductDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProductDetailResponse)
	err := c.cc.Invoke(ctx, ProductDetailService_DeleteProductDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductDetailServiceServer is the server API for ProductDetailService service.
// All implementations must embed UnimplementedProductDetailServiceServer
// for forward compatibility.
type ProductDetailServiceServer interface {
	ListProductDetails(context.Context, *ListProductDetailsRequest) (*ListProductDetailsResponse, error)
	GetProductDetail(context.Context, *GetProductDetailRequest) (*GetProductDetailResponse, error)
	CreateProductDetail(context.Context, *CreateProductDetailRequest) (*CreateProductDetailResponse, error)
	UpdateProductDetail(context.Context, *UpdateProductDetailRequest) (*UpdateProductDetailResponse, error)
	DeleteProductDetail(context.Context, *DeleteProductDetailRequest) (*DeleteProductDetailResponse, error)
	mustEmbedUnimplementedProductDetailServiceServer()
}

// UnimplementedProductDetailServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductDetailServiceServer struct{}

func (UnimplementedProductDetailServiceServer) ListProductDetails(context.Context, *ListProductDetailsRequest) (*ListProductDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProductDetails not implemented")
}
func (UnimplementedProductDetailServiceServer) GetProductDetail(context.Context, *GetProductDetailRequest) (*GetProductDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductDetail not implemented")
}
func (UnimplementedProductDetailServiceServer) CreateProductDetail(context.Context, *CreateProductDetailRequest) (*CreateProductDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProductDetail not implemented")
}
func (UnimplementedProductDetailServiceServer) UpdateProductDetail(context.Context, *UpdateProductDetailRequest) (*UpdateProductDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProductDetail not implemented")
}
func (UnimplementedProductDetailServiceServer) DeleteProductDetail(context.Context, *DeleteProductDetailRequest) (*DeleteProductDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProductDetail not implemented")
}
func (UnimplementedProductDetailServiceServer) mustEmbedUnimplementedProductDetailServiceServer() {}
func (UnimplementedProductDetailServiceServer) testEmbeddedByValue()                              {}

// UnsafeProductDetailServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductDetailServiceServer will
// result in compilation errors.
type UnsafeProductDetailServiceServer interface {
	mustEmbedUnimplementedProductDetailServiceServer()
}

func RegisterProductDetailServiceServer(s grpc.ServiceRegistrar, srv ProductDetailServiceServer) {
	// If the following call panics, it indicates UnimplementedProductDetailServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductDetailService_ServiceDesc, srv)
}

func _ProductDetailService_ListProductDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductDetailServiceServer).ListProductDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductDetailService_ListProductDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductDetailServiceServer).ListProductDetails(ctx, req.(*ListProductDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductDetailService_GetProductDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductDetailServiceServer).GetProductDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductDetailService_GetProductDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductDetailServiceServer).GetProductDetail(ctx, req.(*GetProductDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductDetailService_CreateProductDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductDetailServiceServer).CreateProductDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductDetailService_CreateProductDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductDetailServiceServer).CreateProductDetail(ctx, req.(*CreateProductDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductDetailService_UpdateProductDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductDetailServiceServer).UpdateProductDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductDetailService_UpdateProductDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductDetailServiceServer).UpdateProductDetail(ctx, req.(*UpdateProductDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductDetailService_DeleteProductDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductDetailServiceServer).DeleteProductDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductDetailService_DeleteProductDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductDetailServiceServer).DeleteProductDetail(ctx, req.(*DeleteProductDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductDetailService_ServiceDesc is the grpc.ServiceDesc for ProductDetailService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductDetailService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orcan.v1.ProductDetailService",
	HandlerType: (*ProductDetailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProductDetails",
			Handler:    _ProductDetailService_ListProductDetails_Handler,
		},
		{
			MethodName: "GetProductDetail",
			Handler:    _ProductDetailService_GetProductDetail_Handler,
		},
		{
			MethodName: "CreateProductDetail",
			Handler:    _ProductDetailService_CreateProductDetail_Handler,
		},
		{
			MethodName: "UpdateProductDetail",
			Handler:    _ProductDetailService_UpdateProductDetail_Handler,
		},
		{
			MethodName: "DeleteProductDetail",
			Handler:    _ProductDetailService_DeleteProductDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orcan/v1/product_detail.proto",
}
