// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ConfirmProductAssetInput struct {
	OriginalFilename *string `json:"originalFilename,omitempty"`
	ContentType      *string `json:"contentType,omitempty"`
	FileSize         *int32  `json:"fileSize,omitempty"`
	Description      *string `json:"description,omitempty"`
	SortOrder        *int32  `json:"sortOrder,omitempty"`
	IsPrimary        *bool   `json:"isPrimary,omitempty"`
	Metadata         *string `json:"metadata,omitempty"`
}

type ConfirmProductImageUploadResult struct {
	Product *Product       `json:"product"`
	Detail  *ProductDetail `json:"detail,omitempty"`
}

type CreateProductInput struct {
	UserID      int32   `json:"userId"`
	CategoryID  int32   `json:"categoryId"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	ImageURL    *string `json:"imageUrl,omitempty"`
	Price       int32   `json:"price"`
	Status      *string `json:"status,omitempty"`
}

type Mutation struct {
}

type Product struct {
	ID          int32  `json:"id"`
	UserID      int32  `json:"userId"`
	CategoryID  int32  `json:"categoryId"`
	Name        string `json:"name"`
	Description string `json:"description"`
	ImageURL    string `json:"imageUrl"`
	FileURL     string `json:"fileUrl"`
	Price       int32  `json:"price"`
	Status      string `json:"status"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
	Version     int32  `json:"version"`
}

type ProductAsset struct {
	ID               int32                `json:"id"`
	ProductID        int32                `json:"productId"`
	PurposeID        int32                `json:"purposeId"`
	Purpose          *ProductAssetPurpose `json:"purpose"`
	StorageURL       string               `json:"storageUrl"`
	OriginalFilename string               `json:"originalFilename"`
	ContentType      string               `json:"contentType"`
	FileSize         int32                `json:"fileSize"`
	Description      string               `json:"description"`
	SortOrder        int32                `json:"sortOrder"`
	IsPrimary        bool                 `json:"isPrimary"`
	Metadata         string               `json:"metadata"`
	CreatedAt        string               `json:"createdAt"`
	UpdatedAt        string               `json:"updatedAt"`
}

type ProductAssetPurpose struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	IsPublic bool   `json:"isPublic"`
}

type ProductAssetUploadTarget struct {
	BlobEndpoint string `json:"blobEndpoint"`
	Container    string `json:"container"`
	PathPrefix   string `json:"pathPrefix"`
	SasToken     string `json:"sasToken"`
	ExpiresAt    string `json:"expiresAt"`
}

type ProductDetail struct {
	ID          int32  `json:"id"`
	ProductID   int32  `json:"productId"`
	ImageURL    string `json:"imageUrl"`
	Description string `json:"description"`
	SortOrder   int32  `json:"sortOrder"`
}

type ProductDownloadTarget struct {
	DownloadURL string `json:"downloadUrl"`
	ExpiresAt   string `json:"expiresAt"`
}

type ProductFileUploadTarget struct {
	BlobEndpoint string `json:"blobEndpoint"`
	Container    string `json:"container"`
	PathPrefix   string `json:"pathPrefix"`
	SasToken     string `json:"sasToken"`
	ExpiresAt    string `json:"expiresAt"`
}

type ProductImageUploadTarget struct {
	BlobEndpoint    string `json:"blobEndpoint"`
	Container       string `json:"container"`
	MainImagePrefix string `json:"mainImagePrefix"`
	SubImagesPrefix string `json:"subImagesPrefix"`
	SasToken        string `json:"sasToken"`
	ExpiresAt       string `json:"expiresAt"`
}

type Query struct {
}

type UpdateProductInput struct {
	UserID      int32   `json:"userId"`
	CategoryID  int32   `json:"categoryId"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	ImageURL    *string `json:"imageUrl,omitempty"`
	Price       int32   `json:"price"`
	Status      *string `json:"status,omitempty"`
}

type UpdateUserInput struct {
	Name string `json:"name"`
}

type User struct {
	ID        int32  `json:"id"`
	Email     string `json:"email"`
	Name      string `json:"name"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}
