// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateProductInput struct {
	UserID      int32   `json:"userId"`
	CategoryID  int32   `json:"categoryId"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	ImageURL    *string `json:"imageUrl,omitempty"`
	Price       int32   `json:"price"`
	Status      *string `json:"status,omitempty"`
}

type Mutation struct {
}

type Product struct {
	ID          int32  `json:"id"`
	UserID      int32  `json:"userId"`
	CategoryID  int32  `json:"categoryId"`
	Name        string `json:"name"`
	Description string `json:"description"`
	ImageURL    string `json:"imageUrl"`
	Price       int32  `json:"price"`
	Status      string `json:"status"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type Query struct {
}

type UpdateProductInput struct {
	UserID      int32   `json:"userId"`
	CategoryID  int32   `json:"categoryId"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	ImageURL    *string `json:"imageUrl,omitempty"`
	Price       int32   `json:"price"`
	Status      *string `json:"status,omitempty"`
}

type UpdateUserInput struct {
	Name string `json:"name"`
}

type User struct {
	ID        int32  `json:"id"`
	Email     string `json:"email"`
	Name      string `json:"name"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}
