// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: orcan/v1/product_listing.proto

package orcanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductListing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     uint32                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ListedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=listed_at,json=listedAt,proto3" json:"listed_at,omitempty"`
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductListing) Reset() {
	*x = ProductListing{}
	mi := &file_orcan_v1_product_listing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductListing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductListing) ProtoMessage() {}

func (x *ProductListing) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_listing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductListing.ProtoReflect.Descriptor instead.
func (*ProductListing) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_listing_proto_rawDescGZIP(), []int{0}
}

func (x *ProductListing) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductListing) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductListing) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductListing) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProductListing) GetListedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ListedAt
	}
	return nil
}

func (x *ProductListing) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *ProductListing) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductListing) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListProductListingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     *uint32                `protobuf:"varint,1,opt,name=product_id,json=productId,proto3,oneof" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductListingsRequest) Reset() {
	*x = ListProductListingsRequest{}
	mi := &file_orcan_v1_product_listing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductListingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductListingsRequest) ProtoMessage() {}

func (x *ListProductListingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_listing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductListingsRequest.ProtoReflect.Descriptor instead.
func (*ListProductListingsRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_listing_proto_rawDescGZIP(), []int{1}
}

func (x *ListProductListingsRequest) GetProductId() uint32 {
	if x != nil && x.ProductId != nil {
		return *x.ProductId
	}
	return 0
}

type ListProductListingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listings      []*ProductListing      `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductListingsResponse) Reset() {
	*x = ListProductListingsResponse{}
	mi := &file_orcan_v1_product_listing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductListingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductListingsResponse) ProtoMessage() {}

func (x *ListProductListingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_listing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductListingsResponse.ProtoReflect.Descriptor instead.
func (*ListProductListingsResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_listing_proto_rawDescGZIP(), []int{2}
}

func (x *ListProductListingsResponse) GetListings() []*ProductListing {
	if x != nil {
		return x.Listings
	}
	return nil
}

type GetProductListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductListingRequest) Reset() {
	*x = GetProductListingRequest{}
	mi := &file_orcan_v1_product_listing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductListingRequest) ProtoMessage() {}

func (x *GetProductListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_listing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductListingRequest.ProtoReflect.Descriptor instead.
func (*GetProductListingRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_listing_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductListingRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProductListingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listing       *ProductListing        `protobuf:"bytes,1,opt,name=listing,proto3" json:"listing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductListingResponse) Reset() {
	*x = GetProductListingResponse{}
	mi := &file_orcan_v1_product_listing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductListingResponse) ProtoMessage() {}

func (x *GetProductListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_listing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductListingResponse.ProtoReflect.Descriptor instead.
func (*GetProductListingResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_listing_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductListingResponse) GetListing() *ProductListing {
	if x != nil {
		return x.Listing
	}
	return nil
}

type CreateProductListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Price         int64                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ListedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=listed_at,json=listedAt,proto3" json:"listed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductListingRequest) Reset() {
	*x = CreateProductListingRequest{}
	mi := &file_orcan_v1_product_listing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductListingRequest) ProtoMessage() {}

func (x *CreateProductListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_listing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductListingRequest.ProtoReflect.Descriptor instead.
func (*CreateProductListingRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_listing_proto_rawDescGZIP(), []int{5}
}

func (x *CreateProductListingRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateProductListingRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductListingRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateProductListingRequest) GetListedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ListedAt
	}
	return nil
}

type CreateProductListingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listing       *ProductListing        `protobuf:"bytes,1,opt,name=listing,proto3" json:"listing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductListingResponse) Reset() {
	*x = CreateProductListingResponse{}
	mi := &file_orcan_v1_product_listing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductListingResponse) ProtoMessage() {}

func (x *CreateProductListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_listing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductListingResponse.ProtoReflect.Descriptor instead.
func (*CreateProductListingResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_listing_proto_rawDescGZIP(), []int{6}
}

func (x *CreateProductListingResponse) GetListing() *ProductListing {
	if x != nil {
		return x.Listing
	}
	return nil
}

type UpdateProductListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     uint32                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ListedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=listed_at,json=listedAt,proto3" json:"listed_at,omitempty"`
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductListingRequest) Reset() {
	*x = UpdateProductListingRequest{}
	mi := &file_orcan_v1_product_listing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductListingRequest) ProtoMessage() {}

func (x *UpdateProductListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_listing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductListingRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductListingRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_listing_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProductListingRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductListingRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateProductListingRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateProductListingRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateProductListingRequest) GetListedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ListedAt
	}
	return nil
}

func (x *UpdateProductListingRequest) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

type UpdateProductListingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listing       *ProductListing        `protobuf:"bytes,1,opt,name=listing,proto3" json:"listing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductListingResponse) Reset() {
	*x = UpdateProductListingResponse{}
	mi := &file_orcan_v1_product_listing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductListingResponse) ProtoMessage() {}

func (x *UpdateProductListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_listing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductListingResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductListingResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_listing_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProductListingResponse) GetListing() *ProductListing {
	if x != nil {
		return x.Listing
	}
	return nil
}

type DeleteProductListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductListingRequest) Reset() {
	*x = DeleteProductListingRequest{}
	mi := &file_orcan_v1_product_listing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductListingRequest) ProtoMessage() {}

func (x *DeleteProductListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_listing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductListingRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductListingRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_listing_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteProductListingRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteProductListingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductListingResponse) Reset() {
	*x = DeleteProductListingResponse{}
	mi := &file_orcan_v1_product_listing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductListingResponse) ProtoMessage() {}

func (x *DeleteProductListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_listing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductListingResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductListingResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_listing_proto_rawDescGZIP(), []int{10}
}

var File_orcan_v1_product_listing_proto protoreflect.FileDescriptor

const file_orcan_v1_product_listing_proto_rawDesc = "" +
	"\n" +
	"\x1eorcan/v1/product_listing.proto\x12\borcan.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd3\x02\n" +
	"\x0eProductListing\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\rR\tproductId\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x127\n" +
	"\tlisted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\blistedAt\x125\n" +
	"\bended_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"O\n" +
	"\x1aListProductListingsRequest\x12\"\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rH\x00R\tproductId\x88\x01\x01B\r\n" +
	"\v_product_id\"S\n" +
	"\x1bListProductListingsResponse\x124\n" +
	"\blistings\x18\x01 \x03(\v2\x18.orcan.v1.ProductListingR\blistings\"*\n" +
	"\x18GetProductListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"O\n" +
	"\x19GetProductListingResponse\x122\n" +
	"\alisting\x18\x01 \x01(\v2\x18.orcan.v1.ProductListingR\alisting\"\xa3\x01\n" +
	"\x1bCreateProductListingRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x03R\x05price\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x127\n" +
	"\tlisted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\blistedAt\"R\n" +
	"\x1cCreateProductListingResponse\x122\n" +
	"\alisting\x18\x01 \x01(\v2\x18.orcan.v1.ProductListingR\alisting\"\xea\x01\n" +
	"\x1bUpdateProductListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\rR\tproductId\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x127\n" +
	"\tlisted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\blistedAt\x125\n" +
	"\bended_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\"R\n" +
	"\x1cUpdateProductListingResponse\x122\n" +
	"\alisting\x18\x01 \x01(\v2\x18.orcan.v1.ProductListingR\alisting\"-\n" +
	"\x1bDeleteProductListingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x1e\n" +
	"\x1cDeleteProductListingResponse2\x8e\x04\n" +
	"\x15ProductListingService\x12b\n" +
	"\x13ListProductListings\x12$.orcan.v1.ListProductListingsRequest\x1a%.orcan.v1.ListProductListingsResponse\x12\\\n" +
	"\x11GetProductListing\x12\".orcan.v1.GetProductListingRequest\x1a#.orcan.v1.GetProductListingResponse\x12e\n" +
	"\x14CreateProductListing\x12%.orcan.v1.CreateProductListingRequest\x1a&.orcan.v1.CreateProductListingResponse\x12e\n" +
	"\x14UpdateProductListing\x12%.orcan.v1.UpdateProductListingRequest\x1a&.orcan.v1.UpdateProductListingResponse\x12e\n" +
	"\x14DeleteProductListing\x12%.orcan.v1.DeleteProductListingRequest\x1a&.orcan.v1.DeleteProductListingResponseBQZOgithub.com/asamigentoku/PinguCoin/server/orcan-api/internal/pb/orcan/v1;orcanv1b\x06proto3"

var (
	file_orcan_v1_product_listing_proto_rawDescOnce sync.Once
	file_orcan_v1_product_listing_proto_rawDescData []byte
)

func file_orcan_v1_product_listing_proto_rawDescGZIP() []byte {
	file_orcan_v1_product_listing_proto_rawDescOnce.Do(func() {
		file_orcan_v1_product_listing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orcan_v1_product_listing_proto_rawDesc), len(file_orcan_v1_product_listing_proto_rawDesc)))
	})
	return file_orcan_v1_product_listing_proto_rawDescData
}

var file_orcan_v1_product_listing_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_orcan_v1_product_listing_proto_goTypes = []any{
	(*ProductListing)(nil),               // 0: orcan.v1.ProductListing
	(*ListProductListingsRequest)(nil),   // 1: orcan.v1.ListProductListingsRequest
	(*ListProductListingsResponse)(nil),  // 2: orcan.v1.ListProductListingsResponse
	(*GetProductListingRequest)(nil),     // 3: orcan.v1.GetProductListingRequest
	(*GetProductListingResponse)(nil),    // 4: orcan.v1.GetProductListingResponse
	(*CreateProductListingRequest)(nil),  // 5: orcan.v1.CreateProductListingRequest
	(*CreateProductListingResponse)(nil), // 6: orcan.v1.CreateProductListingResponse
	(*UpdateProductListingRequest)(nil),  // 7: orcan.v1.UpdateProductListingRequest
	(*UpdateProductListingResponse)(nil), // 8: orcan.v1.UpdateProductListingResponse
	(*DeleteProductListingRequest)(nil),  // 9: orcan.v1.DeleteProductListingRequest
	(*DeleteProductListingResponse)(nil), // 10: orcan.v1.DeleteProductListingResponse
	(*timestamppb.Timestamp)(nil),        // 11: google.protobuf.Timestamp
}
var file_orcan_v1_product_listing_proto_depIdxs = []int32{
	11, // 0: orcan.v1.ProductListing.listed_at:type_name -> google.protobuf.Timestamp
	11, // 1: orcan.v1.ProductListing.ended_at:type_name -> google.protobuf.Timestamp
	11, // 2: orcan.v1.ProductListing.created_at:type_name -> google.protobuf.Timestamp
	11, // 3: orcan.v1.ProductListing.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: orcan.v1.ListProductListingsResponse.listings:type_name -> orcan.v1.ProductListing
	0,  // 5: orcan.v1.GetProductListingResponse.listing:type_name -> orcan.v1.ProductListing
	11, // 6: orcan.v1.CreateProductListingRequest.listed_at:type_name -> google.protobuf.Timestamp
	0,  // 7: orcan.v1.CreateProductListingResponse.listing:type_name -> orcan.v1.ProductListing
	11, // 8: orcan.v1.UpdateProductListingRequest.listed_at:type_name -> google.protobuf.Timestamp
	11, // 9: orcan.v1.UpdateProductListingRequest.ended_at:type_name -> google.protobuf.Timestamp
	0,  // 10: orcan.v1.UpdateProductListingResponse.listing:type_name -> orcan.v1.ProductListing
	1,  // 11: orcan.v1.ProductListingService.ListProductListings:input_type -> orcan.v1.ListProductListingsRequest
	3,  // 12: orcan.v1.ProductListingService.GetProductListing:input_type -> orcan.v1.GetProductListingRequest
	5,  // 13: orcan.v1.ProductListingService.CreateProductListing:input_type -> orcan.v1.CreateProductListingRequest
	7,  // 14: orcan.v1.ProductListingService.UpdateProductListing:input_type -> orcan.v1.UpdateProductListingRequest
	9,  // 15: orcan.v1.ProductListingService.DeleteProductListing:input_type -> orcan.v1.DeleteProductListingRequest
	2,  // 16: orcan.v1.ProductListingService.ListProductListings:output_type -> orcan.v1.ListProductListingsResponse
	4,  // 17: orcan.v1.ProductListingService.GetProductListing:output_type -> orcan.v1.GetProductListingResponse
	6,  // 18: orcan.v1.ProductListingService.CreateProductListing:output_type -> orcan.v1.CreateProductListingResponse
	8,  // 19: orcan.v1.ProductListingService.UpdateProductListing:output_type -> orcan.v1.UpdateProductListingResponse
	10, // 20: orcan.v1.ProductListingService.DeleteProductListing:output_type -> orcan.v1.DeleteProductListingResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_orcan_v1_product_listing_proto_init() }
func file_orcan_v1_product_listing_proto_init() {
	if File_orcan_v1_product_listing_proto != nil {
		return
	}
	file_orcan_v1_product_listing_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orcan_v1_product_listing_proto_rawDesc), len(file_orcan_v1_product_listing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orcan_v1_product_listing_proto_goTypes,
		DependencyIndexes: file_orcan_v1_product_listing_proto_depIdxs,
		MessageInfos:      file_orcan_v1_product_listing_proto_msgTypes,
	}.Build()
	File_orcan_v1_product_listing_proto = out.File
	file_orcan_v1_product_listing_proto_goTypes = nil
	file_orcan_v1_product_listing_proto_depIdxs = nil
}
