// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: orcan/v1/product_inventory.proto

package orcanv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductInventoryService_ListProductInventories_FullMethodName = "/orcan.v1.ProductInventoryService/ListProductInventories"
	ProductInventoryService_GetProductInventory_FullMethodName    = "/orcan.v1.ProductInventoryService/GetProductInventory"
	ProductInventoryService_CreateProductInventory_FullMethodName = "/orcan.v1.ProductInventoryService/CreateProductInventory"
	ProductInventoryService_UpdateProductInventory_FullMethodName = "/orcan.v1.ProductInventoryService/UpdateProductInventory"
	ProductInventoryService_DeleteProductInventory_FullMethodName = "/orcan.v1.ProductInventoryService/DeleteProductInventory"
	ProductInventoryService_AdjustProductInventory_FullMethodName = "/orcan.v1.ProductInventoryService/AdjustProductInventory"
)

// ProductInventoryServiceClient is the client API for ProductInventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductInventoryServiceClient interface {
	ListProductInventories(ctx context.Context, in *ListProductInventoriesRequest, opts ...grpc.CallOption) (*ListProductInventoriesResponse, error)
	GetProductInventory(ctx context.Context, in *GetProductInventoryRequest, opts ...grpc.CallOption) (*GetProductInventoryResponse, error)
	CreateProductInventory(ctx context.Context, in *CreateProductInventoryRequest, opts ...grpc.CallOption) (*CreateProductInventoryResponse, error)
	UpdateProductInventory(ctx context.Context, in *UpdateProductInventoryRequest, opts ...grpc.CallOption) (*UpdateProductInventoryResponse, error)
	DeleteProductInventory(ctx context.Context, in *DeleteProductInventoryRequest, opts ...grpc.CallOption) (*DeleteProductInventoryResponse, error)
	// AdjustProductInventory は在庫数(quantity)をamountだけ増減させる(負=消費、正=戻し)。
	// idempotency_keyが同じリクエストを再送しても在庫が二重に増減することはない
	// (最初に処理した結果をそのまま返す)。在庫が不足する場合はFAILED_PRECONDITIONを返す。
	AdjustProductInventory(ctx context.Context, in *AdjustProductInventoryRequest, opts ...grpc.CallOption) (*AdjustProductInventoryResponse, error)
}

type productInventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductInventoryServiceClient(cc grpc.ClientConnInterface) ProductInventoryServiceClient {
	return &productInventoryServiceClient{cc}
}

func (c *productInventoryServiceClient) ListProductInventories(ctx context.Context, in *ListProductInventoriesRequest, opts ...grpc.CallOption) (*ListProductInventoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProductInventoriesResponse)
	err := c.cc.Invoke(ctx, ProductInventoryService_ListProductInventories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productInventoryServiceClient) GetProductInventory(ctx context.Context, in *GetProductInventoryRequest, opts ...grpc.CallOption) (*GetProductInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductInventoryResponse)
	err := c.cc.Invoke(ctx, ProductInventoryService_GetProductInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productInventoryServiceClient) CreateProductInventory(ctx context.Context, in *CreateProductInventoryRequest, opts ...grpc.CallOption) (*CreateProductInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProductInventoryResponse)
	err := c.cc.Invoke(ctx, ProductInventoryService_CreateProductInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productInventoryServiceClient) UpdateProductInventory(ctx context.Context, in *UpdateProductInventoryRequest, opts ...grpc.CallOption) (*UpdateProductInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProductInventoryResponse)
	err := c.cc.Invoke(ctx, ProductInventoryService_UpdateProductInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productInventoryServiceClient) DeleteProductInventory(ctx context.Context, in *DeleteProductInventoryRequest, opts ...grpc.CallOption) (*DeleteProductInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProductInventoryResponse)
	err := c.cc.Invoke(ctx, ProductInventoryService_DeleteProductInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productInventoryServiceClient) AdjustProductInventory(ctx context.Context, in *AdjustProductInventoryRequest, opts ...grpc.CallOption) (*AdjustProductInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdjustProductInventoryResponse)
	err := c.cc.Invoke(ctx, ProductInventoryService_AdjustProductInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductInventoryServiceServer is the server API for ProductInventoryService service.
// All implementations must embed UnimplementedProductInventoryServiceServer
// for forward compatibility.
type ProductInventoryServiceServer interface {
	ListProductInventories(context.Context, *ListProductInventoriesRequest) (*ListProductInventoriesResponse, error)
	GetProductInventory(context.Context, *GetProductInventoryRequest) (*GetProductInventoryResponse, error)
	CreateProductInventory(context.Context, *CreateProductInventoryRequest) (*CreateProductInventoryResponse, error)
	UpdateProductInventory(context.Context, *UpdateProductInventoryRequest) (*UpdateProductInventoryResponse, error)
	DeleteProductInventory(context.Context, *DeleteProductInventoryRequest) (*DeleteProductInventoryResponse, error)
	// AdjustProductInventory は在庫数(quantity)をamountだけ増減させる(負=消費、正=戻し)。
	// idempotency_keyが同じリクエストを再送しても在庫が二重に増減することはない
	// (最初に処理した結果をそのまま返す)。在庫が不足する場合はFAILED_PRECONDITIONを返す。
	AdjustProductInventory(context.Context, *AdjustProductInventoryRequest) (*AdjustProductInventoryResponse, error)
	mustEmbedUnimplementedProductInventoryServiceServer()
}

// UnimplementedProductInventoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductInventoryServiceServer struct{}

func (UnimplementedProductInventoryServiceServer) ListProductInventories(context.Context, *ListProductInventoriesRequest) (*ListProductInventoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProductInventories not implemented")
}
func (UnimplementedProductInventoryServiceServer) GetProductInventory(context.Context, *GetProductInventoryRequest) (*GetProductInventoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductInventory not implemented")
}
func (UnimplementedProductInventoryServiceServer) CreateProductInventory(context.Context, *CreateProductInventoryRequest) (*CreateProductInventoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProductInventory not implemented")
}
func (UnimplementedProductInventoryServiceServer) UpdateProductInventory(context.Context, *UpdateProductInventoryRequest) (*UpdateProductInventoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProductInventory not implemented")
}
func (UnimplementedProductInventoryServiceServer) DeleteProductInventory(context.Context, *DeleteProductInventoryRequest) (*DeleteProductInventoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProductInventory not implemented")
}
func (UnimplementedProductInventoryServiceServer) AdjustProductInventory(context.Context, *AdjustProductInventoryRequest) (*AdjustProductInventoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdjustProductInventory not implemented")
}
func (UnimplementedProductInventoryServiceServer) mustEmbedUnimplementedProductInventoryServiceServer() {
}
func (UnimplementedProductInventoryServiceServer) testEmbeddedByValue() {}

// UnsafeProductInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductInventoryServiceServer will
// result in compilation errors.
type UnsafeProductInventoryServiceServer interface {
	mustEmbedUnimplementedProductInventoryServiceServer()
}

func RegisterProductInventoryServiceServer(s grpc.ServiceRegistrar, srv ProductInventoryServiceServer) {
	// If the following call panics, it indicates UnimplementedProductInventoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductInventoryService_ServiceDesc, srv)
}

func _ProductInventoryService_ListProductInventories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductInventoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductInventoryServiceServer).ListProductInventories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductInventoryService_ListProductInventories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductInventoryServiceServer).ListProductInventories(ctx, req.(*ListProductInventoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductInventoryService_GetProductInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductInventoryServiceServer).GetProductInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductInventoryService_GetProductInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductInventoryServiceServer).GetProductInventory(ctx, req.(*GetProductInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductInventoryService_CreateProductInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductInventoryServiceServer).CreateProductInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductInventoryService_CreateProductInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductInventoryServiceServer).CreateProductInventory(ctx, req.(*CreateProductInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductInventoryService_UpdateProductInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductInventoryServiceServer).UpdateProductInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductInventoryService_UpdateProductInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductInventoryServiceServer).UpdateProductInventory(ctx, req.(*UpdateProductInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductInventoryService_DeleteProductInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductInventoryServiceServer).DeleteProductInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductInventoryService_DeleteProductInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductInventoryServiceServer).DeleteProductInventory(ctx, req.(*DeleteProductInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductInventoryService_AdjustProductInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdjustProductInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductInventoryServiceServer).AdjustProductInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductInventoryService_AdjustProductInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductInventoryServiceServer).AdjustProductInventory(ctx, req.(*AdjustProductInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductInventoryService_ServiceDesc is the grpc.ServiceDesc for ProductInventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductInventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orcan.v1.ProductInventoryService",
	HandlerType: (*ProductInventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProductInventories",
			Handler:    _ProductInventoryService_ListProductInventories_Handler,
		},
		{
			MethodName: "GetProductInventory",
			Handler:    _ProductInventoryService_GetProductInventory_Handler,
		},
		{
			MethodName: "CreateProductInventory",
			Handler:    _ProductInventoryService_CreateProductInventory_Handler,
		},
		{
			MethodName: "UpdateProductInventory",
			Handler:    _ProductInventoryService_UpdateProductInventory_Handler,
		},
		{
			MethodName: "DeleteProductInventory",
			Handler:    _ProductInventoryService_DeleteProductInventory_Handler,
		},
		{
			MethodName: "AdjustProductInventory",
			Handler:    _ProductInventoryService_AdjustProductInventory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orcan/v1/product_inventory.proto",
}
