// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: orcan/v1/product_category.proto

package orcanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      *uint32                `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductCategory) Reset() {
	*x = ProductCategory{}
	mi := &file_orcan_v1_product_category_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCategory) ProtoMessage() {}

func (x *ProductCategory) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_category_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCategory.ProtoReflect.Descriptor instead.
func (*ProductCategory) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_category_proto_rawDescGZIP(), []int{0}
}

func (x *ProductCategory) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductCategory) GetParentId() uint32 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *ProductCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductCategory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductCategory) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListProductCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductCategoriesRequest) Reset() {
	*x = ListProductCategoriesRequest{}
	mi := &file_orcan_v1_product_category_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductCategoriesRequest) ProtoMessage() {}

func (x *ListProductCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_category_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListProductCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_category_proto_rawDescGZIP(), []int{1}
}

type ListProductCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*ProductCategory     `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductCategoriesResponse) Reset() {
	*x = ListProductCategoriesResponse{}
	mi := &file_orcan_v1_product_category_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductCategoriesResponse) ProtoMessage() {}

func (x *ListProductCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_category_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListProductCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_category_proto_rawDescGZIP(), []int{2}
}

func (x *ListProductCategoriesResponse) GetCategories() []*ProductCategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

type GetProductCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductCategoryRequest) Reset() {
	*x = GetProductCategoryRequest{}
	mi := &file_orcan_v1_product_category_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductCategoryRequest) ProtoMessage() {}

func (x *GetProductCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_category_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetProductCategoryRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_category_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductCategoryRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProductCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *ProductCategory       `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductCategoryResponse) Reset() {
	*x = GetProductCategoryResponse{}
	mi := &file_orcan_v1_product_category_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductCategoryResponse) ProtoMessage() {}

func (x *GetProductCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_category_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductCategoryResponse.ProtoReflect.Descriptor instead.
func (*GetProductCategoryResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_category_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductCategoryResponse) GetCategory() *ProductCategory {
	if x != nil {
		return x.Category
	}
	return nil
}

type CreateProductCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      *uint32                `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductCategoryRequest) Reset() {
	*x = CreateProductCategoryRequest{}
	mi := &file_orcan_v1_product_category_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductCategoryRequest) ProtoMessage() {}

func (x *CreateProductCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_category_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateProductCategoryRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_category_proto_rawDescGZIP(), []int{5}
}

func (x *CreateProductCategoryRequest) GetParentId() uint32 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *CreateProductCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateProductCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *ProductCategory       `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductCategoryResponse) Reset() {
	*x = CreateProductCategoryResponse{}
	mi := &file_orcan_v1_product_category_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductCategoryResponse) ProtoMessage() {}

func (x *CreateProductCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_category_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductCategoryResponse.ProtoReflect.Descriptor instead.
func (*CreateProductCategoryResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_category_proto_rawDescGZIP(), []int{6}
}

func (x *CreateProductCategoryResponse) GetCategory() *ProductCategory {
	if x != nil {
		return x.Category
	}
	return nil
}

type UpdateProductCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      *uint32                `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductCategoryRequest) Reset() {
	*x = UpdateProductCategoryRequest{}
	mi := &file_orcan_v1_product_category_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductCategoryRequest) ProtoMessage() {}

func (x *UpdateProductCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_category_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductCategoryRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_category_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProductCategoryRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductCategoryRequest) GetParentId() uint32 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *UpdateProductCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateProductCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *ProductCategory       `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductCategoryResponse) Reset() {
	*x = UpdateProductCategoryResponse{}
	mi := &file_orcan_v1_product_category_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductCategoryResponse) ProtoMessage() {}

func (x *UpdateProductCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_category_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductCategoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductCategoryResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_category_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProductCategoryResponse) GetCategory() *ProductCategory {
	if x != nil {
		return x.Category
	}
	return nil
}

type DeleteProductCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductCategoryRequest) Reset() {
	*x = DeleteProductCategoryRequest{}
	mi := &file_orcan_v1_product_category_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductCategoryRequest) ProtoMessage() {}

func (x *DeleteProductCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_category_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductCategoryRequest) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_category_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteProductCategoryRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteProductCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductCategoryResponse) Reset() {
	*x = DeleteProductCategoryResponse{}
	mi := &file_orcan_v1_product_category_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductCategoryResponse) ProtoMessage() {}

func (x *DeleteProductCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orcan_v1_product_category_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductCategoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductCategoryResponse) Descriptor() ([]byte, []int) {
	return file_orcan_v1_product_category_proto_rawDescGZIP(), []int{10}
}

var File_orcan_v1_product_category_proto protoreflect.FileDescriptor

const file_orcan_v1_product_category_proto_rawDesc = "" +
	"\n" +
	"\x1forcan/v1/product_category.proto\x12\borcan.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x01\n" +
	"\x0fProductCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12 \n" +
	"\tparent_id\x18\x02 \x01(\rH\x00R\bparentId\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\f\n" +
	"\n" +
	"_parent_id\"\x1e\n" +
	"\x1cListProductCategoriesRequest\"Z\n" +
	"\x1dListProductCategoriesResponse\x129\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x19.orcan.v1.ProductCategoryR\n" +
	"categories\"+\n" +
	"\x19GetProductCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"S\n" +
	"\x1aGetProductCategoryResponse\x125\n" +
	"\bcategory\x18\x01 \x01(\v2\x19.orcan.v1.ProductCategoryR\bcategory\"b\n" +
	"\x1cCreateProductCategoryRequest\x12 \n" +
	"\tparent_id\x18\x01 \x01(\rH\x00R\bparentId\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameB\f\n" +
	"\n" +
	"_parent_id\"V\n" +
	"\x1dCreateProductCategoryResponse\x125\n" +
	"\bcategory\x18\x01 \x01(\v2\x19.orcan.v1.ProductCategoryR\bcategory\"r\n" +
	"\x1cUpdateProductCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12 \n" +
	"\tparent_id\x18\x02 \x01(\rH\x00R\bparentId\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04nameB\f\n" +
	"\n" +
	"_parent_id\"V\n" +
	"\x1dUpdateProductCategoryResponse\x125\n" +
	"\bcategory\x18\x01 \x01(\v2\x19.orcan.v1.ProductCategoryR\bcategory\".\n" +
	"\x1cDeleteProductCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x1f\n" +
	"\x1dDeleteProductCategoryResponse2\xa1\x04\n" +
	"\x16ProductCategoryService\x12h\n" +
	"\x15ListProductCategories\x12&.orcan.v1.ListProductCategoriesRequest\x1a'.orcan.v1.ListProductCategoriesResponse\x12_\n" +
	"\x12GetProductCategory\x12#.orcan.v1.GetProductCategoryRequest\x1a$.orcan.v1.GetProductCategoryResponse\x12h\n" +
	"\x15CreateProductCategory\x12&.orcan.v1.CreateProductCategoryRequest\x1a'.orcan.v1.CreateProductCategoryResponse\x12h\n" +
	"\x15UpdateProductCategory\x12&.orcan.v1.UpdateProductCategoryRequest\x1a'.orcan.v1.UpdateProductCategoryResponse\x12h\n" +
	"\x15DeleteProductCategory\x12&.orcan.v1.DeleteProductCategoryRequest\x1a'.orcan.v1.DeleteProductCategoryResponseBQZOgithub.com/asamigentoku/PinguCoin/server/orcan-api/internal/pb/orcan/v1;orcanv1b\x06proto3"

var (
	file_orcan_v1_product_category_proto_rawDescOnce sync.Once
	file_orcan_v1_product_category_proto_rawDescData []byte
)

func file_orcan_v1_product_category_proto_rawDescGZIP() []byte {
	file_orcan_v1_product_category_proto_rawDescOnce.Do(func() {
		file_orcan_v1_product_category_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orcan_v1_product_category_proto_rawDesc), len(file_orcan_v1_product_category_proto_rawDesc)))
	})
	return file_orcan_v1_product_category_proto_rawDescData
}

var file_orcan_v1_product_category_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_orcan_v1_product_category_proto_goTypes = []any{
	(*ProductCategory)(nil),               // 0: orcan.v1.ProductCategory
	(*ListProductCategoriesRequest)(nil),  // 1: orcan.v1.ListProductCategoriesRequest
	(*ListProductCategoriesResponse)(nil), // 2: orcan.v1.ListProductCategoriesResponse
	(*GetProductCategoryRequest)(nil),     // 3: orcan.v1.GetProductCategoryRequest
	(*GetProductCategoryResponse)(nil),    // 4: orcan.v1.GetProductCategoryResponse
	(*CreateProductCategoryRequest)(nil),  // 5: orcan.v1.CreateProductCategoryRequest
	(*CreateProductCategoryResponse)(nil), // 6: orcan.v1.CreateProductCategoryResponse
	(*UpdateProductCategoryRequest)(nil),  // 7: orcan.v1.UpdateProductCategoryRequest
	(*UpdateProductCategoryResponse)(nil), // 8: orcan.v1.UpdateProductCategoryResponse
	(*DeleteProductCategoryRequest)(nil),  // 9: orcan.v1.DeleteProductCategoryRequest
	(*DeleteProductCategoryResponse)(nil), // 10: orcan.v1.DeleteProductCategoryResponse
	(*timestamppb.Timestamp)(nil),         // 11: google.protobuf.Timestamp
}
var file_orcan_v1_product_category_proto_depIdxs = []int32{
	11, // 0: orcan.v1.ProductCategory.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: orcan.v1.ProductCategory.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: orcan.v1.ListProductCategoriesResponse.categories:type_name -> orcan.v1.ProductCategory
	0,  // 3: orcan.v1.GetProductCategoryResponse.category:type_name -> orcan.v1.ProductCategory
	0,  // 4: orcan.v1.CreateProductCategoryResponse.category:type_name -> orcan.v1.ProductCategory
	0,  // 5: orcan.v1.UpdateProductCategoryResponse.category:type_name -> orcan.v1.ProductCategory
	1,  // 6: orcan.v1.ProductCategoryService.ListProductCategories:input_type -> orcan.v1.ListProductCategoriesRequest
	3,  // 7: orcan.v1.ProductCategoryService.GetProductCategory:input_type -> orcan.v1.GetProductCategoryRequest
	5,  // 8: orcan.v1.ProductCategoryService.CreateProductCategory:input_type -> orcan.v1.CreateProductCategoryRequest
	7,  // 9: orcan.v1.ProductCategoryService.UpdateProductCategory:input_type -> orcan.v1.UpdateProductCategoryRequest
	9,  // 10: orcan.v1.ProductCategoryService.DeleteProductCategory:input_type -> orcan.v1.DeleteProductCategoryRequest
	2,  // 11: orcan.v1.ProductCategoryService.ListProductCategories:output_type -> orcan.v1.ListProductCategoriesResponse
	4,  // 12: orcan.v1.ProductCategoryService.GetProductCategory:output_type -> orcan.v1.GetProductCategoryResponse
	6,  // 13: orcan.v1.ProductCategoryService.CreateProductCategory:output_type -> orcan.v1.CreateProductCategoryResponse
	8,  // 14: orcan.v1.ProductCategoryService.UpdateProductCategory:output_type -> orcan.v1.UpdateProductCategoryResponse
	10, // 15: orcan.v1.ProductCategoryService.DeleteProductCategory:output_type -> orcan.v1.DeleteProductCategoryResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_orcan_v1_product_category_proto_init() }
func file_orcan_v1_product_category_proto_init() {
	if File_orcan_v1_product_category_proto != nil {
		return
	}
	file_orcan_v1_product_category_proto_msgTypes[0].OneofWrappers = []any{}
	file_orcan_v1_product_category_proto_msgTypes[5].OneofWrappers = []any{}
	file_orcan_v1_product_category_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orcan_v1_product_category_proto_rawDesc), len(file_orcan_v1_product_category_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orcan_v1_product_category_proto_goTypes,
		DependencyIndexes: file_orcan_v1_product_category_proto_depIdxs,
		MessageInfos:      file_orcan_v1_product_category_proto_msgTypes,
	}.Build()
	File_orcan_v1_product_category_proto = out.File
	file_orcan_v1_product_category_proto_goTypes = nil
	file_orcan_v1_product_category_proto_depIdxs = nil
}
