// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: payment/v1/point.proto

package paymentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PointAccount はユーザーごとのポイント残高(user_idごとに1件)。
type PointAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointAccount) Reset() {
	*x = PointAccount{}
	mi := &file_payment_v1_point_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointAccount) ProtoMessage() {}

func (x *PointAccount) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_point_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointAccount.ProtoReflect.Descriptor instead.
func (*PointAccount) Descriptor() ([]byte, []int) {
	return file_payment_v1_point_proto_rawDescGZIP(), []int{0}
}

func (x *PointAccount) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PointAccount) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *PointAccount) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// PointTransaction はポイントの増減履歴。1件が1回の付与/消費に対応する。
type PointTransaction struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"` // 正の値=付与、負の値=消費
	Type   string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`      // "credit" / "debit" / "payment" / "refund"
	// Payment(決済)に紐づく増減(point払い/その返金)の場合のみ設定される。
	PaymentId     *uint32                `protobuf:"varint,5,opt,name=payment_id,json=paymentId,proto3,oneof" json:"payment_id,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	BalanceAfter  int64                  `protobuf:"varint,7,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointTransaction) Reset() {
	*x = PointTransaction{}
	mi := &file_payment_v1_point_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointTransaction) ProtoMessage() {}

func (x *PointTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_point_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointTransaction.ProtoReflect.Descriptor instead.
func (*PointTransaction) Descriptor() ([]byte, []int) {
	return file_payment_v1_point_proto_rawDescGZIP(), []int{1}
}

func (x *PointTransaction) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PointTransaction) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PointTransaction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PointTransaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PointTransaction) GetPaymentId() uint32 {
	if x != nil && x.PaymentId != nil {
		return *x.PaymentId
	}
	return 0
}

func (x *PointTransaction) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PointTransaction) GetBalanceAfter() int64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *PointTransaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetPointAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPointAccountRequest) Reset() {
	*x = GetPointAccountRequest{}
	mi := &file_payment_v1_point_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPointAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPointAccountRequest) ProtoMessage() {}

func (x *GetPointAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_point_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPointAccountRequest.ProtoReflect.Descriptor instead.
func (*GetPointAccountRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_point_proto_rawDescGZIP(), []int{2}
}

func (x *GetPointAccountRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetPointAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *PointAccount          `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPointAccountResponse) Reset() {
	*x = GetPointAccountResponse{}
	mi := &file_payment_v1_point_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPointAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPointAccountResponse) ProtoMessage() {}

func (x *GetPointAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_point_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPointAccountResponse.ProtoReflect.Descriptor instead.
func (*GetPointAccountResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_point_proto_rawDescGZIP(), []int{3}
}

func (x *GetPointAccountResponse) GetAccount() *PointAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

type ListPointTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *uint32                `protobuf:"varint,1,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPointTransactionsRequest) Reset() {
	*x = ListPointTransactionsRequest{}
	mi := &file_payment_v1_point_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPointTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPointTransactionsRequest) ProtoMessage() {}

func (x *ListPointTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_point_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPointTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListPointTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_point_proto_rawDescGZIP(), []int{4}
}

func (x *ListPointTransactionsRequest) GetUserId() uint32 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

type ListPointTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*PointTransaction    `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPointTransactionsResponse) Reset() {
	*x = ListPointTransactionsResponse{}
	mi := &file_payment_v1_point_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPointTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPointTransactionsResponse) ProtoMessage() {}

func (x *ListPointTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_point_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPointTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListPointTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_point_proto_rawDescGZIP(), []int{5}
}

func (x *ListPointTransactionsResponse) GetTransactions() []*PointTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type CreditPointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"` // 正の値を指定する
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditPointsRequest) Reset() {
	*x = CreditPointsRequest{}
	mi := &file_payment_v1_point_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditPointsRequest) ProtoMessage() {}

func (x *CreditPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_point_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditPointsRequest.ProtoReflect.Descriptor instead.
func (*CreditPointsRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_point_proto_rawDescGZIP(), []int{6}
}

func (x *CreditPointsRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreditPointsRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreditPointsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CreditPointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *PointTransaction      `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Account       *PointAccount          `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditPointsResponse) Reset() {
	*x = CreditPointsResponse{}
	mi := &file_payment_v1_point_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditPointsResponse) ProtoMessage() {}

func (x *CreditPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_point_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditPointsResponse.ProtoReflect.Descriptor instead.
func (*CreditPointsResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_point_proto_rawDescGZIP(), []int{7}
}

func (x *CreditPointsResponse) GetTransaction() *PointTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *CreditPointsResponse) GetAccount() *PointAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

type DebitPointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"` // 正の値を指定する(内部で残高から減算する)
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebitPointsRequest) Reset() {
	*x = DebitPointsRequest{}
	mi := &file_payment_v1_point_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebitPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebitPointsRequest) ProtoMessage() {}

func (x *DebitPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_point_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebitPointsRequest.ProtoReflect.Descriptor instead.
func (*DebitPointsRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_point_proto_rawDescGZIP(), []int{8}
}

func (x *DebitPointsRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DebitPointsRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DebitPointsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DebitPointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *PointTransaction      `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Account       *PointAccount          `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebitPointsResponse) Reset() {
	*x = DebitPointsResponse{}
	mi := &file_payment_v1_point_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebitPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebitPointsResponse) ProtoMessage() {}

func (x *DebitPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_point_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebitPointsResponse.ProtoReflect.Descriptor instead.
func (*DebitPointsResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_point_proto_rawDescGZIP(), []int{9}
}

func (x *DebitPointsResponse) GetTransaction() *PointTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *DebitPointsResponse) GetAccount() *PointAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

var File_payment_v1_point_proto protoreflect.FileDescriptor

const file_payment_v1_point_proto_rawDesc = "" +
	"\n" +
	"\x16payment/v1/point.proto\x12\n" +
	"payment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"|\n" +
	"\fPointAccount\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x92\x02\n" +
	"\x10PointTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\"\n" +
	"\n" +
	"payment_id\x18\x05 \x01(\rH\x00R\tpaymentId\x88\x01\x01\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12#\n" +
	"\rbalance_after\x18\a \x01(\x03R\fbalanceAfter\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\r\n" +
	"\v_payment_id\"1\n" +
	"\x16GetPointAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"M\n" +
	"\x17GetPointAccountResponse\x122\n" +
	"\aaccount\x18\x01 \x01(\v2\x18.payment.v1.PointAccountR\aaccount\"H\n" +
	"\x1cListPointTransactionsRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\rH\x00R\x06userId\x88\x01\x01B\n" +
	"\n" +
	"\b_user_id\"a\n" +
	"\x1dListPointTransactionsResponse\x12@\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1c.payment.v1.PointTransactionR\ftransactions\"^\n" +
	"\x13CreditPointsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x8a\x01\n" +
	"\x14CreditPointsResponse\x12>\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1c.payment.v1.PointTransactionR\vtransaction\x122\n" +
	"\aaccount\x18\x02 \x01(\v2\x18.payment.v1.PointAccountR\aaccount\"]\n" +
	"\x12DebitPointsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x89\x01\n" +
	"\x13DebitPointsResponse\x12>\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1c.payment.v1.PointTransactionR\vtransaction\x122\n" +
	"\aaccount\x18\x02 \x01(\v2\x18.payment.v1.PointAccountR\aaccount2\xfb\x02\n" +
	"\fPointService\x12Z\n" +
	"\x0fGetPointAccount\x12\".payment.v1.GetPointAccountRequest\x1a#.payment.v1.GetPointAccountResponse\x12l\n" +
	"\x15ListPointTransactions\x12(.payment.v1.ListPointTransactionsRequest\x1a).payment.v1.ListPointTransactionsResponse\x12Q\n" +
	"\fCreditPoints\x12\x1f.payment.v1.CreditPointsRequest\x1a .payment.v1.CreditPointsResponse\x12N\n" +
	"\vDebitPoints\x12\x1e.payment.v1.DebitPointsRequest\x1a\x1f.payment.v1.DebitPointsResponseBWZUgithub.com/asamigentoku/PinguCoin/server/payment-api/internal/pb/payment/v1;paymentv1b\x06proto3"

var (
	file_payment_v1_point_proto_rawDescOnce sync.Once
	file_payment_v1_point_proto_rawDescData []byte
)

func file_payment_v1_point_proto_rawDescGZIP() []byte {
	file_payment_v1_point_proto_rawDescOnce.Do(func() {
		file_payment_v1_point_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_v1_point_proto_rawDesc), len(file_payment_v1_point_proto_rawDesc)))
	})
	return file_payment_v1_point_proto_rawDescData
}

var file_payment_v1_point_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_payment_v1_point_proto_goTypes = []any{
	(*PointAccount)(nil),                  // 0: payment.v1.PointAccount
	(*PointTransaction)(nil),              // 1: payment.v1.PointTransaction
	(*GetPointAccountRequest)(nil),        // 2: payment.v1.GetPointAccountRequest
	(*GetPointAccountResponse)(nil),       // 3: payment.v1.GetPointAccountResponse
	(*ListPointTransactionsRequest)(nil),  // 4: payment.v1.ListPointTransactionsRequest
	(*ListPointTransactionsResponse)(nil), // 5: payment.v1.ListPointTransactionsResponse
	(*CreditPointsRequest)(nil),           // 6: payment.v1.CreditPointsRequest
	(*CreditPointsResponse)(nil),          // 7: payment.v1.CreditPointsResponse
	(*DebitPointsRequest)(nil),            // 8: payment.v1.DebitPointsRequest
	(*DebitPointsResponse)(nil),           // 9: payment.v1.DebitPointsResponse
	(*timestamppb.Timestamp)(nil),         // 10: google.protobuf.Timestamp
}
var file_payment_v1_point_proto_depIdxs = []int32{
	10, // 0: payment.v1.PointAccount.updated_at:type_name -> google.protobuf.Timestamp
	10, // 1: payment.v1.PointTransaction.created_at:type_name -> google.protobuf.Timestamp
	0,  // 2: payment.v1.GetPointAccountResponse.account:type_name -> payment.v1.PointAccount
	1,  // 3: payment.v1.ListPointTransactionsResponse.transactions:type_name -> payment.v1.PointTransaction
	1,  // 4: payment.v1.CreditPointsResponse.transaction:type_name -> payment.v1.PointTransaction
	0,  // 5: payment.v1.CreditPointsResponse.account:type_name -> payment.v1.PointAccount
	1,  // 6: payment.v1.DebitPointsResponse.transaction:type_name -> payment.v1.PointTransaction
	0,  // 7: payment.v1.DebitPointsResponse.account:type_name -> payment.v1.PointAccount
	2,  // 8: payment.v1.PointService.GetPointAccount:input_type -> payment.v1.GetPointAccountRequest
	4,  // 9: payment.v1.PointService.ListPointTransactions:input_type -> payment.v1.ListPointTransactionsRequest
	6,  // 10: payment.v1.PointService.CreditPoints:input_type -> payment.v1.CreditPointsRequest
	8,  // 11: payment.v1.PointService.DebitPoints:input_type -> payment.v1.DebitPointsRequest
	3,  // 12: payment.v1.PointService.GetPointAccount:output_type -> payment.v1.GetPointAccountResponse
	5,  // 13: payment.v1.PointService.ListPointTransactions:output_type -> payment.v1.ListPointTransactionsResponse
	7,  // 14: payment.v1.PointService.CreditPoints:output_type -> payment.v1.CreditPointsResponse
	9,  // 15: payment.v1.PointService.DebitPoints:output_type -> payment.v1.DebitPointsResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_payment_v1_point_proto_init() }
func file_payment_v1_point_proto_init() {
	if File_payment_v1_point_proto != nil {
		return
	}
	file_payment_v1_point_proto_msgTypes[1].OneofWrappers = []any{}
	file_payment_v1_point_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_v1_point_proto_rawDesc), len(file_payment_v1_point_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_v1_point_proto_goTypes,
		DependencyIndexes: file_payment_v1_point_proto_depIdxs,
		MessageInfos:      file_payment_v1_point_proto_msgTypes,
	}.Build()
	File_payment_v1_point_proto = out.File
	file_payment_v1_point_proto_goTypes = nil
	file_payment_v1_point_proto_depIdxs = nil
}
