// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: payment/v1/point.proto

package paymentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PointService_GetPointAccount_FullMethodName       = "/payment.v1.PointService/GetPointAccount"
	PointService_ListPointTransactions_FullMethodName = "/payment.v1.PointService/ListPointTransactions"
	PointService_CreditPoints_FullMethodName          = "/payment.v1.PointService/CreditPoints"
	PointService_DebitPoints_FullMethodName           = "/payment.v1.PointService/DebitPoints"
)

// PointServiceClient is the client API for PointService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PointServiceClient interface {
	// 残高取得
	GetPointAccount(ctx context.Context, in *GetPointAccountRequest, opts ...grpc.CallOption) (*GetPointAccountResponse, error)
	// 履歴取得
	ListPointTransactions(ctx context.Context, in *ListPointTransactionsRequest, opts ...grpc.CallOption) (*ListPointTransactionsResponse, error)
	// 決済連携以外の手動付与・消費(例: キャンペーン付与、運用による調整)
	CreditPoints(ctx context.Context, in *CreditPointsRequest, opts ...grpc.CallOption) (*CreditPointsResponse, error)
	DebitPoints(ctx context.Context, in *DebitPointsRequest, opts ...grpc.CallOption) (*DebitPointsResponse, error)
}

type pointServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPointServiceClient(cc grpc.ClientConnInterface) PointServiceClient {
	return &pointServiceClient{cc}
}

func (c *pointServiceClient) GetPointAccount(ctx context.Context, in *GetPointAccountRequest, opts ...grpc.CallOption) (*GetPointAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPointAccountResponse)
	err := c.cc.Invoke(ctx, PointService_GetPointAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointServiceClient) ListPointTransactions(ctx context.Context, in *ListPointTransactionsRequest, opts ...grpc.CallOption) (*ListPointTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPointTransactionsResponse)
	err := c.cc.Invoke(ctx, PointService_ListPointTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointServiceClient) CreditPoints(ctx context.Context, in *CreditPointsRequest, opts ...grpc.CallOption) (*CreditPointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreditPointsResponse)
	err := c.cc.Invoke(ctx, PointService_CreditPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointServiceClient) DebitPoints(ctx context.Context, in *DebitPointsRequest, opts ...grpc.CallOption) (*DebitPointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DebitPointsResponse)
	err := c.cc.Invoke(ctx, PointService_DebitPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PointServiceServer is the server API for PointService service.
// All implementations must embed UnimplementedPointServiceServer
// for forward compatibility.
type PointServiceServer interface {
	// 残高取得
	GetPointAccount(context.Context, *GetPointAccountRequest) (*GetPointAccountResponse, error)
	// 履歴取得
	ListPointTransactions(context.Context, *ListPointTransactionsRequest) (*ListPointTransactionsResponse, error)
	// 決済連携以外の手動付与・消費(例: キャンペーン付与、運用による調整)
	CreditPoints(context.Context, *CreditPointsRequest) (*CreditPointsResponse, error)
	DebitPoints(context.Context, *DebitPointsRequest) (*DebitPointsResponse, error)
	mustEmbedUnimplementedPointServiceServer()
}

// UnimplementedPointServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPointServiceServer struct{}

func (UnimplementedPointServiceServer) GetPointAccount(context.Context, *GetPointAccountRequest) (*GetPointAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPointAccount not implemented")
}
func (UnimplementedPointServiceServer) ListPointTransactions(context.Context, *ListPointTransactionsRequest) (*ListPointTransactionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPointTransactions not implemented")
}
func (UnimplementedPointServiceServer) CreditPoints(context.Context, *CreditPointsRequest) (*CreditPointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreditPoints not implemented")
}
func (UnimplementedPointServiceServer) DebitPoints(context.Context, *DebitPointsRequest) (*DebitPointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DebitPoints not implemented")
}
func (UnimplementedPointServiceServer) mustEmbedUnimplementedPointServiceServer() {}
func (UnimplementedPointServiceServer) testEmbeddedByValue()                      {}

// UnsafePointServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PointServiceServer will
// result in compilation errors.
type UnsafePointServiceServer interface {
	mustEmbedUnimplementedPointServiceServer()
}

func RegisterPointServiceServer(s grpc.ServiceRegistrar, srv PointServiceServer) {
	// If the following call panics, it indicates UnimplementedPointServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PointService_ServiceDesc, srv)
}

func _PointService_GetPointAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPointAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServiceServer).GetPointAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointService_GetPointAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServiceServer).GetPointAccount(ctx, req.(*GetPointAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointService_ListPointTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPointTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServiceServer).ListPointTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointService_ListPointTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServiceServer).ListPointTransactions(ctx, req.(*ListPointTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointService_CreditPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreditPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServiceServer).CreditPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointService_CreditPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServiceServer).CreditPoints(ctx, req.(*CreditPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointService_DebitPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DebitPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServiceServer).DebitPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointService_DebitPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServiceServer).DebitPoints(ctx, req.(*DebitPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PointService_ServiceDesc is the grpc.ServiceDesc for PointService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PointService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.v1.PointService",
	HandlerType: (*PointServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPointAccount",
			Handler:    _PointService_GetPointAccount_Handler,
		},
		{
			MethodName: "ListPointTransactions",
			Handler:    _PointService_ListPointTransactions_Handler,
		},
		{
			MethodName: "CreditPoints",
			Handler:    _PointService_CreditPoints_Handler,
		},
		{
			MethodName: "DebitPoints",
			Handler:    _PointService_DebitPoints_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment/v1/point.proto",
}
